"use strict";
(function() {
  const C = [
    // ───────── USA ─────────
    {
      id: "mit",
      name: "Massachusetts Institute of Technology",
      country: "USA",
      city: "Cambridge, MA",
      rank: 1,
      natRank: 2,
      type: "Private",
      founded: 1861,
      website: "mit.edu",
      programs: ["MS Computer Science", "MS EECS", "MBA (Sloan)", "MS Data Science", "MS Mechanical Eng"],
      ielts: 7,
      toefl: 90,
      pte: 65,
      duolingo: 120,
      gre: "Optional",
      gmat: 730,
      gpa: "3.5/4.0",
      workEx: "5 yrs (MBA)",
      tuitionUSD: 58e3,
      feeNote: "$58k/yr",
      appFee: "$75",
      scholarship: "Need-based aid + research/teaching assistantships",
      intakes: ["Fall (Sep)"],
      deadline: "Dec 15 (Fall)",
      acceptance: 4,
      intlPct: 33,
      classProfile: "Avg GRE 322 \xB7 GPA 3.7",
      strengths: ["Engineering", "Computer Science", "AI"],
      alumni: "Kofi Annan, Buzz Aldrin",
      highlight: "World #1 for engineering & technology."
    },
    {
      id: "stanford",
      name: "Stanford University",
      country: "USA",
      city: "Stanford, CA",
      rank: 6,
      natRank: 3,
      type: "Private",
      founded: 1885,
      website: "stanford.edu",
      programs: ["MS Computer Science", "MS AI", "MBA (GSB)", "MS Management Science", "MS Electrical Eng"],
      ielts: 7,
      toefl: 100,
      pte: 68,
      duolingo: 125,
      gre: "Optional",
      gmat: 738,
      gpa: "3.5/4.0",
      workEx: "4\u20135 yrs (MBA)",
      tuitionUSD: 58e3,
      feeNote: "$58k/yr",
      appFee: "$125",
      scholarship: "Knight-Hennessy (fully funded) + dept aid",
      intakes: ["Fall (Sep)"],
      deadline: "Dec 1 (Fall)",
      acceptance: 4,
      intlPct: 24,
      classProfile: "Avg GMAT 738 \xB7 GPA 3.8",
      strengths: ["Computer Science", "Entrepreneurship", "MBA"],
      alumni: "Sundar Pichai, Elon Musk (briefly)",
      highlight: "Heart of Silicon Valley; elite CS & MBA."
    },
    {
      id: "cmu",
      name: "Carnegie Mellon University",
      country: "USA",
      city: "Pittsburgh, PA",
      rank: 52,
      natRank: 24,
      type: "Private",
      founded: 1900,
      website: "cmu.edu",
      programs: ["MS Computer Science", "MS Data Science", "MS AI", "MS Information Systems", "MS Robotics"],
      ielts: 7,
      toefl: 100,
      pte: 68,
      duolingo: 120,
      gre: "Recommended",
      gmat: 700,
      gpa: "3.3/4.0",
      workEx: null,
      tuitionUSD: 5e4,
      feeNote: "$48\u201352k/yr",
      appFee: "$75",
      scholarship: "Merit aid + assistantships",
      intakes: ["Fall (Sep)"],
      deadline: "Dec 1 (Fall)",
      acceptance: 11,
      intlPct: 50,
      classProfile: "Avg GRE 325 (Quant) \xB7 GPA 3.6",
      strengths: ["Computer Science", "AI/ML", "Robotics"],
      alumni: "Andy Warhol, Vinod Khosla",
      highlight: "#1 graduate CS school in the US."
    },
    {
      id: "gatech",
      name: "Georgia Institute of Technology",
      country: "USA",
      city: "Atlanta, GA",
      rank: 80,
      natRank: 33,
      type: "Public",
      founded: 1885,
      website: "gatech.edu",
      programs: ["MS Computer Science", "MS Analytics", "MS Electrical Eng", "OMSCS (online)", "MS Cybersecurity"],
      ielts: 7,
      toefl: 90,
      pte: 65,
      duolingo: 115,
      gre: "Optional",
      gmat: 680,
      gpa: "3.0/4.0",
      workEx: null,
      tuitionUSD: 31e3,
      feeNote: "$30\u201333k/yr",
      appFee: "$85",
      scholarship: "GRA/GTA assistantships (tuition waiver + stipend)",
      intakes: ["Fall (Sep)", "Spring (Jan)"],
      deadline: "Jan 15 (Fall)",
      acceptance: 17,
      intlPct: 45,
      classProfile: "Avg GRE 320 \xB7 GPA 3.5",
      strengths: ["Engineering", "Analytics", "CS"],
      alumni: "Jimmy Carter (briefly)",
      highlight: "Top engineering at public-school value."
    },
    {
      id: "berkeley",
      name: "University of California, Berkeley",
      country: "USA",
      city: "Berkeley, CA",
      rank: 12,
      natRank: 17,
      type: "Public",
      founded: 1868,
      website: "berkeley.edu",
      programs: ["MEng", "MS EECS", "Master of Analytics", "MBA (Haas)", "MS Data Science"],
      ielts: 7,
      toefl: 90,
      pte: 68,
      duolingo: 120,
      gre: "Optional",
      gmat: 720,
      gpa: "3.3/4.0",
      workEx: "5 yrs (MBA)",
      tuitionUSD: 34e3,
      feeNote: "$30\u201338k/yr",
      appFee: "$140",
      scholarship: "Limited merit + fellowships",
      intakes: ["Fall (Sep)"],
      deadline: "Dec\u2013Jan (varies)",
      acceptance: 11,
      intlPct: 30,
      classProfile: "Avg GRE 322 \xB7 GPA 3.7",
      strengths: ["EECS", "Data Science", "Business"],
      alumni: "Steve Wozniak, Eric Schmidt",
      highlight: "Top public research university."
    },
    {
      id: "uiuc",
      name: "University of Illinois Urbana-Champaign",
      country: "USA",
      city: "Urbana, IL",
      rank: 64,
      natRank: 33,
      type: "Public",
      founded: 1867,
      website: "illinois.edu",
      programs: ["MS Computer Science", "MS ECE", "MS Data Science", "MBA", "MS Information Management"],
      ielts: 6.5,
      toefl: 79,
      pte: 60,
      duolingo: 115,
      gre: "Optional",
      gmat: 650,
      gpa: "3.0/4.0",
      workEx: null,
      tuitionUSD: 35e3,
      feeNote: "$33\u201338k/yr",
      appFee: "$90",
      scholarship: "Assistantships + departmental aid",
      intakes: ["Fall (Sep)", "Spring (Jan)"],
      deadline: "Dec 15 (Fall)",
      acceptance: 45,
      intlPct: 24,
      classProfile: "Avg GRE 318 \xB7 GPA 3.4",
      strengths: ["Computer Science", "Engineering", "Accountancy"],
      alumni: "Marc Andreessen, Jawed Karim",
      highlight: "Powerhouse for CS & engineering."
    },
    {
      id: "nyu",
      name: "New York University",
      country: "USA",
      city: "New York, NY",
      rank: 38,
      natRank: 30,
      type: "Private",
      founded: 1831,
      website: "nyu.edu",
      programs: ["MS Computer Science", "MS Data Science", "MBA (Stern)", "MS Finance", "MS Information Systems"],
      ielts: 7,
      toefl: 100,
      pte: 68,
      duolingo: 120,
      gre: "Optional",
      gmat: 710,
      gpa: "3.3/4.0",
      workEx: "4 yrs (MBA)",
      tuitionUSD: 52e3,
      feeNote: "$50\u201355k/yr",
      appFee: "$110",
      scholarship: "Merit scholarships + assistantships",
      intakes: ["Fall (Sep)", "Spring (Jan)"],
      deadline: "Dec\u2013Feb (varies)",
      acceptance: 12,
      intlPct: 35,
      classProfile: "Avg GMAT 733 \xB7 GPA 3.6",
      strengths: ["Business", "Data Science", "Law"],
      alumni: "Lady Gaga, Martin Scorsese",
      highlight: "Prime NYC location; strong business & tech."
    },
    {
      id: "usc",
      name: "University of Southern California",
      country: "USA",
      city: "Los Angeles, CA",
      rank: 116,
      natRank: 28,
      type: "Private",
      founded: 1880,
      website: "usc.edu",
      programs: ["MS Computer Science", "MS Data Science", "MS Electrical Eng", "MS Business Analytics", "MS Cybersecurity"],
      ielts: 6.5,
      toefl: 90,
      pte: 65,
      duolingo: 115,
      gre: "Optional",
      gmat: 680,
      gpa: "3.0/4.0",
      workEx: null,
      tuitionUSD: 5e4,
      feeNote: "$48\u201352k/yr",
      appFee: "$90",
      scholarship: "Merit scholarships (Viterbi) + assistantships",
      intakes: ["Fall (Sep)", "Spring (Jan)"],
      deadline: "Dec 15 (Fall)",
      acceptance: 12,
      intlPct: 25,
      classProfile: "Avg GRE 320 \xB7 GPA 3.5",
      strengths: ["Engineering", "Film", "Business"],
      alumni: "Neil Armstrong, George Lucas",
      highlight: "Large Indian community; strong alumni network."
    },
    { id: "harvard", name: "Harvard University", country: "USA", city: "Cambridge, MA", rank: 4, natRank: 3, type: "Private", founded: 1636, website: "harvard.edu", programs: ["MS Computer Science", "MBA (HBS)", "MS Data Science", "Master in Public Policy", "MS Engineering"], ielts: 7, gre: "Optional", gmat: 740, gpa: "3.7/4.0", tuitionUSD: 54e3, feeNote: "$54k/yr", intakes: ["Fall (Sep)"], deadline: "Dec 1", acceptance: 4, scholarship: "Need-based aid + fellowships", strengths: ["Business", "Law", "Medicine"], highlight: "World's most famous university." },
    { id: "columbia", name: "Columbia University", country: "USA", city: "New York, NY", rank: 23, natRank: 12, type: "Private", founded: 1754, website: "columbia.edu", programs: ["MS Computer Science", "MS Data Science", "MBA", "MS Financial Eng", "MS Electrical Eng"], ielts: 7, gre: "Optional", gmat: 730, gpa: "3.5/4.0", tuitionUSD: 53e3, feeNote: "$50\u201356k/yr", intakes: ["Fall (Sep)", "Spring (Jan)"], deadline: "Dec 15 (Fall)", acceptance: 12, scholarship: "Merit + dept assistantships", strengths: ["Finance", "Data Science", "Journalism"], highlight: "Ivy League in the heart of NYC." },
    { id: "cornell", name: "Cornell University", country: "USA", city: "Ithaca, NY", rank: 16, natRank: 12, type: "Private", founded: 1865, website: "cornell.edu", programs: ["MEng Computer Science", "MS Data Science", "MBA (Johnson)", "MEng ECE", "MPS Applied Stats"], ielts: 7, gre: "Optional", gmat: 710, gpa: "3.3/4.0", tuitionUSD: 52e3, feeNote: "$50\u201355k/yr", intakes: ["Fall (Sep)"], deadline: "Feb 1 (Fall)", acceptance: 11, scholarship: "Tata Scholarship (India), assistantships", strengths: ["Engineering", "Hotel Mgmt", "Agriculture"], highlight: "Ivy League with strong tech & ag." },
    { id: "ucla", name: "University of California, Los Angeles", country: "USA", city: "Los Angeles, CA", rank: 42, natRank: 15, type: "Public", founded: 1919, website: "ucla.edu", programs: ["MS Computer Science", "MS Data Science", "MBA (Anderson)", "MS Electrical Eng", "MS Engineering"], ielts: 7, gre: "Optional", gmat: 710, gpa: "3.3/4.0", tuitionUSD: 32e3, feeNote: "$30\u201335k/yr", intakes: ["Fall (Sep)"], deadline: "Dec 1 (Fall)", acceptance: 9, scholarship: "Graduate Division fellowships", strengths: ["CS", "Film", "Business"], highlight: "Top public university in California." },
    { id: "umich", name: "University of Michigan, Ann Arbor", country: "USA", city: "Ann Arbor, MI", rank: 44, natRank: 21, type: "Public", founded: 1817, website: "umich.edu", programs: ["MS Computer Science", "MS Data Science", "MBA (Ross)", "MS Information", "MS Engineering"], ielts: 7, gre: "Optional", gmat: 720, gpa: "3.3/4.0", tuitionUSD: 33e3, feeNote: "$32\u201338k/yr", intakes: ["Fall (Sep)"], deadline: "Dec\u2013Jan", acceptance: 18, scholarship: "Merit + assistantships", strengths: ["Engineering", "Business", "Information"], highlight: "Elite public research university." },
    { id: "utaustin", name: "University of Texas at Austin", country: "USA", city: "Austin, TX", rank: 58, natRank: 30, type: "Public", founded: 1883, website: "utexas.edu", programs: ["MS Computer Science", "MS Data Science", "MBA (McCombs)", "MS ECE", "MS Business Analytics"], ielts: 6.5, gre: "Optional", gmat: 700, gpa: "3.0/4.0", tuitionUSD: 22e3, feeNote: "$20\u201324k/yr", intakes: ["Fall (Sep)"], deadline: "Dec 1 (Fall)", acceptance: 30, scholarship: "Assistantships + fellowships", strengths: ["CS", "Engineering", "Business"], highlight: "Top CS at low public tuition; booming Austin tech." },
    { id: "uwseattle", name: "University of Washington", country: "USA", city: "Seattle, WA", rank: 63, natRank: 40, type: "Public", founded: 1861, website: "washington.edu", programs: ["MS Computer Science", "MS Data Science", "MBA (Foster)", "MS ECE", "MS Information"], ielts: 7, gre: "Optional", gmat: 690, gpa: "3.0/4.0", tuitionUSD: 33e3, feeNote: "$31\u201336k/yr", intakes: ["Fall (Sep)"], deadline: "Dec 15 (Fall)", acceptance: 25, scholarship: "Assistantships", strengths: ["CS", "Medicine", "Engineering"], highlight: "Next to Amazon & Microsoft HQs." },
    { id: "purdue", name: "Purdue University", country: "USA", city: "West Lafayette, IN", rank: 89, natRank: 46, type: "Public", founded: 1869, website: "purdue.edu", programs: ["MS Computer Science", "MS ECE", "MS Data Science", "MS Mechanical Eng", "MS Industrial Eng"], ielts: 6.5, gre: "Optional", gmat: 650, gpa: "3.0/4.0", tuitionUSD: 3e4, feeNote: "$28\u201332k/yr", intakes: ["Fall (Sep)", "Spring (Jan)"], deadline: "Dec 15", acceptance: 50, scholarship: "Assistantships (tuition + stipend)", strengths: ["Engineering", "CS", "Aviation"], highlight: "Engineering powerhouse, very Indian-friendly." },
    { id: "northeastern", name: "Northeastern University", country: "USA", city: "Boston, MA", rank: 160, natRank: 53, type: "Private", founded: 1898, website: "northeastern.edu", programs: ["MS Computer Science", "MS Data Science", "MS Information Systems", "MS Analytics", "MBA"], ielts: 6.5, gre: "Optional", gmat: 650, gpa: "3.0/4.0", tuitionUSD: 28e3, feeNote: "$27\u201330k/yr", intakes: ["Fall (Sep)", "Spring (Jan)"], deadline: "Rolling", acceptance: 53, scholarship: "Merit scholarships + co-op earnings", strengths: ["Co-op/internships", "CS", "Analytics"], highlight: "Famous co-op program; strong job outcomes." },
    { id: "ucsd", name: "University of California, San Diego", country: "USA", city: "La Jolla, CA", rank: 72, natRank: 28, type: "Public", founded: 1960, website: "ucsd.edu", programs: ["MS Computer Science", "MS Data Science", "MS ECE", "MS Bioinformatics", "MEng"], ielts: 7, gre: "Optional", gmat: 680, gpa: "3.0/4.0", tuitionUSD: 32e3, feeNote: "$30\u201335k/yr", intakes: ["Fall (Sep)"], deadline: "Dec\u2013Jan", acceptance: 24, scholarship: "Assistantships", strengths: ["CS", "Bioengineering", "Data Science"], highlight: "Top research university in sunny San Diego." },
    // ───────── UK ─────────
    {
      id: "oxford",
      name: "University of Oxford",
      country: "UK",
      city: "Oxford",
      rank: 3,
      natRank: 1,
      type: "Public",
      founded: 1096,
      website: "ox.ac.uk",
      programs: ["MSc Computer Science", "MBA (Sa\xEFd)", "MSc Financial Economics", "MSc Data Science", "MPhil Economics"],
      ielts: 7.5,
      toefl: 110,
      pte: 76,
      duolingo: 130,
      gre: "Optional",
      gmat: 690,
      gpa: "3.7/4.0 (First/2:1)",
      workEx: "5 yrs (MBA)",
      tuitionUSD: 48e3,
      feeNote: "\xA338k/yr",
      appFee: "\xA375",
      scholarship: "Rhodes, Clarendon, Reach Oxford",
      intakes: ["Sep/Oct"],
      deadline: "Jan (most courses)",
      acceptance: 14,
      intlPct: 45,
      classProfile: "Top 5% academically",
      strengths: ["All disciplines", "Research", "PPE"],
      alumni: "27 UK PMs, Stephen Hawking",
      highlight: "One-year master's; globally #1\u20133 ranked."
    },
    {
      id: "cambridge",
      name: "University of Cambridge",
      country: "UK",
      city: "Cambridge",
      rank: 5,
      natRank: 2,
      type: "Public",
      founded: 1209,
      website: "cam.ac.uk",
      programs: ["MPhil Advanced CS", "MBA (Judge)", "MPhil Finance", "MPhil Machine Learning", "MASt Mathematics"],
      ielts: 7.5,
      toefl: 110,
      pte: 76,
      duolingo: 130,
      gre: "Optional",
      gmat: 690,
      gpa: "3.7/4.0 (First/2:1)",
      workEx: "3 yrs (MBA)",
      tuitionUSD: 48e3,
      feeNote: "\xA338k/yr",
      appFee: "\xA375",
      scholarship: "Gates Cambridge (fully funded), Cambridge Trust",
      intakes: ["Sep/Oct"],
      deadline: "Dec\u2013Jan (course-specific)",
      acceptance: 16,
      intlPct: 38,
      classProfile: "Top 5% academically",
      strengths: ["Sciences", "Mathematics", "Engineering"],
      alumni: "Isaac Newton, Charles Darwin",
      highlight: "Historic prestige; intensive one-year programs."
    },
    {
      id: "imperial",
      name: "Imperial College London",
      country: "UK",
      city: "London",
      rank: 2,
      natRank: 3,
      type: "Public",
      founded: 1907,
      website: "imperial.ac.uk",
      programs: ["MSc Computing", "MSc Business Analytics", "MSc Finance", "MSc Machine Learning", "MSc Climate Change"],
      ielts: 7,
      toefl: 100,
      pte: 69,
      duolingo: 125,
      gre: "Optional",
      gmat: 650,
      gpa: "3.3/4.0 (2:1)",
      workEx: null,
      tuitionUSD: 5e4,
      feeNote: "\xA340k/yr",
      appFee: "Free",
      scholarship: "President's PhD, dept scholarships",
      intakes: ["Sep/Oct"],
      deadline: "Rolling (apply early)",
      acceptance: 14,
      intlPct: 60,
      classProfile: "Strong STEM background",
      strengths: ["Engineering", "Medicine", "Business"],
      alumni: "Brian May, H.G. Wells",
      highlight: "STEM-focused; strong industry links."
    },
    {
      id: "ucl",
      name: "University College London (UCL)",
      country: "UK",
      city: "London",
      rank: 9,
      natRank: 4,
      type: "Public",
      founded: 1826,
      website: "ucl.ac.uk",
      programs: ["MSc Computer Science", "MSc Data Science", "MSc Management", "MSc ML", "MSc Finance"],
      ielts: 6.5,
      toefl: 92,
      pte: 62,
      duolingo: 120,
      gre: "Optional",
      gmat: 600,
      gpa: "3.3/4.0 (2:1)",
      workEx: null,
      tuitionUSD: 44e3,
      feeNote: "\xA335k/yr",
      appFee: "\xA390",
      scholarship: "UCL Global Masters, Commonwealth",
      intakes: ["Sep/Oct"],
      deadline: "Rolling",
      acceptance: 30,
      intlPct: 53,
      classProfile: "2:1 honours equivalent",
      strengths: ["Research", "AI", "Architecture"],
      alumni: "Mahatma Gandhi, Christopher Nolan",
      highlight: "Broad program range in central London."
    },
    {
      id: "lse",
      name: "London School of Economics (LSE)",
      country: "UK",
      city: "London",
      rank: 50,
      natRank: 5,
      type: "Public",
      founded: 1895,
      website: "lse.ac.uk",
      programs: ["MSc Economics", "MSc Finance", "MSc Data Science", "MBA", "MSc Management"],
      ielts: 7,
      toefl: 100,
      pte: 69,
      duolingo: 125,
      gre: "Recommended",
      gmat: 650,
      gpa: "3.5/4.0 (2:1)",
      workEx: null,
      tuitionUSD: 48e3,
      feeNote: "\xA338k/yr",
      appFee: "\xA380",
      scholarship: "Graduate Support Scheme, country awards",
      intakes: ["Sep/Oct"],
      deadline: "Rolling (apply by Jan)",
      acceptance: 9,
      intlPct: 70,
      classProfile: "Avg GMAT 710 \xB7 strong quant",
      strengths: ["Economics", "Finance", "Social Science"],
      alumni: "John F. Kennedy, 18 Nobel laureates",
      highlight: "World-leading for economics & social science."
    },
    {
      id: "manchester",
      name: "University of Manchester",
      country: "UK",
      city: "Manchester",
      rank: 34,
      natRank: 6,
      type: "Public",
      founded: 1824,
      website: "manchester.ac.uk",
      programs: ["MSc Computer Science", "MSc Data Science", "MSc Management", "MSc Finance", "MSc AI"],
      ielts: 6.5,
      toefl: 90,
      pte: 60,
      duolingo: 115,
      gre: "Optional",
      gmat: 600,
      gpa: "3.0/4.0 (2:1)",
      workEx: null,
      tuitionUSD: 34e3,
      feeNote: "\xA327k/yr",
      appFee: "Free",
      scholarship: "Global Futures, country bursaries",
      intakes: ["Sep"],
      deadline: "Rolling",
      acceptance: 56,
      intlPct: 40,
      classProfile: "2:1 honours equivalent",
      strengths: ["Engineering", "Business", "Computer Science"],
      alumni: "Alan Turing, 25 Nobel laureates",
      highlight: "Large, popular with international students."
    },
    {
      id: "edinburgh",
      name: "University of Edinburgh",
      country: "UK",
      city: "Edinburgh",
      rank: 27,
      natRank: 7,
      type: "Public",
      founded: 1583,
      website: "ed.ac.uk",
      programs: ["MSc Artificial Intelligence", "MSc Data Science", "MSc Finance", "MSc CS", "MSc Informatics"],
      ielts: 6.5,
      toefl: 92,
      pte: 62,
      duolingo: 120,
      gre: "Optional",
      gmat: 600,
      gpa: "3.0/4.0 (2:1)",
      workEx: null,
      tuitionUSD: 4e4,
      feeNote: "\xA332k/yr",
      appFee: "Free",
      scholarship: "Edinburgh Global, Commonwealth",
      intakes: ["Sep"],
      deadline: "Rolling (rounds)",
      acceptance: 40,
      intlPct: 45,
      classProfile: "2:1 honours equivalent",
      strengths: ["AI/Informatics", "Medicine", "Data Science"],
      alumni: "Charles Darwin, Gordon Brown",
      highlight: "Renowned AI & informatics school."
    },
    { id: "kcl", name: "King's College London", country: "UK", city: "London", rank: 40, natRank: 8, type: "Public", founded: 1829, website: "kcl.ac.uk", programs: ["MSc Computer Science", "MSc Data Science", "MSc AI", "MSc Finance", "MSc International Management"], ielts: 6.5, gre: "Optional", gmat: 600, gpa: "3.0/4.0 (2:1)", tuitionUSD: 4e4, feeNote: "\xA332k/yr", intakes: ["Sep"], deadline: "Rolling", acceptance: 35, scholarship: "King's International Scholarships", strengths: ["Medicine", "Law", "AI"], highlight: "Prestigious central-London Russell Group." },
    { id: "warwick", name: "University of Warwick", country: "UK", city: "Coventry", rank: 69, natRank: 9, type: "Public", founded: 1965, website: "warwick.ac.uk", programs: ["MSc Computer Science", "MSc Data Analytics", "MSc Business Analytics", "MBA (WBS)", "MSc Finance"], ielts: 6.5, gre: "Optional", gmat: 600, gpa: "3.0/4.0 (2:1)", tuitionUSD: 38e3, feeNote: "\xA330k/yr", intakes: ["Sep"], deadline: "Rolling", acceptance: 40, scholarship: "Chancellor's International, country awards", strengths: ["Business", "Economics", "CS"], highlight: "Top UK business & analytics school." },
    { id: "bristol", name: "University of Bristol", country: "UK", city: "Bristol", rank: 54, natRank: 10, type: "Public", founded: 1876, website: "bristol.ac.uk", programs: ["MSc Computer Science", "MSc Data Science", "MSc AI", "MSc Engineering", "MSc Economics"], ielts: 6.5, gre: "Optional", gmat: 600, gpa: "3.0/4.0 (2:1)", tuitionUSD: 35e3, feeNote: "\xA328k/yr", intakes: ["Sep"], deadline: "Rolling", acceptance: 45, scholarship: "Think Big scholarships", strengths: ["Engineering", "AI", "Economics"], highlight: "Leading research university in SW England." },
    { id: "glasgow", name: "University of Glasgow", country: "UK", city: "Glasgow", rank: 76, natRank: 12, type: "Public", founded: 1451, website: "gla.ac.uk", programs: ["MSc Computing Science", "MSc Data Science", "MSc Data Analytics", "MSc Finance", "MSc IT"], ielts: 6.5, gre: "Optional", gmat: 600, gpa: "3.0/4.0 (2:1)", tuitionUSD: 32e3, feeNote: "\xA326k/yr", intakes: ["Sep", "Jan"], deadline: "Rolling", acceptance: 50, scholarship: "Glasgow International Leadership", strengths: ["Computing", "Engineering", "Medicine"], highlight: "Historic Russell Group; two intakes." },
    { id: "birmingham", name: "University of Birmingham", country: "UK", city: "Birmingham", rank: 80, natRank: 14, type: "Public", founded: 1900, website: "birmingham.ac.uk", programs: ["MSc Computer Science", "MSc Data Science", "MSc AI & ML", "MBA", "MSc Financial Mgmt"], ielts: 6.5, gre: "Optional", gmat: 600, gpa: "3.0/4.0 (2:1)", tuitionUSD: 33e3, feeNote: "\xA327k/yr", intakes: ["Sep"], deadline: "Rolling", acceptance: 50, scholarship: "Global Masters Scholarship", strengths: ["Engineering", "Business", "CS"], highlight: "Founding 'red brick' Russell Group university." },
    { id: "leeds", name: "University of Leeds", country: "UK", city: "Leeds", rank: 82, natRank: 15, type: "Public", founded: 1904, website: "leeds.ac.uk", programs: ["MSc Computer Science", "MSc Data Science & Analytics", "MSc AI", "MBA", "MSc Finance"], ielts: 6.5, gre: "Optional", gmat: 600, gpa: "3.0/4.0 (2:1)", tuitionUSD: 32e3, feeNote: "\xA326k/yr", intakes: ["Sep"], deadline: "Rolling", acceptance: 55, scholarship: "Leeds International Scholarships", strengths: ["Business", "Engineering", "Media"], highlight: "Large, popular Russell Group campus." },
    { id: "southampton", name: "University of Southampton", country: "UK", city: "Southampton", rank: 80, natRank: 16, type: "Public", founded: 1862, website: "southampton.ac.uk", programs: ["MSc Computer Science", "MSc Data Science", "MSc AI", "MSc Electronic Eng", "MSc Finance"], ielts: 6.5, gre: "Optional", gmat: 600, gpa: "3.0/4.0 (2:1)", tuitionUSD: 32e3, feeNote: "\xA326k/yr", intakes: ["Sep"], deadline: "Rolling", acceptance: 50, scholarship: "Presidential & country scholarships", strengths: ["Electronics", "CS", "Maritime"], highlight: "Top for electronics & computer science." },
    { id: "sheffield", name: "University of Sheffield", country: "UK", city: "Sheffield", rank: 105, natRank: 17, type: "Public", founded: 1905, website: "sheffield.ac.uk", programs: ["MSc Computer Science", "MSc Data Science", "MSc AI", "MSc Advanced Eng", "MSc Management"], ielts: 6.5, gre: "Optional", gmat: 600, gpa: "3.0/4.0 (2:1)", tuitionUSD: 3e4, feeNote: "\xA325k/yr", intakes: ["Sep"], deadline: "Rolling", acceptance: 58, scholarship: "Postgraduate scholarships", strengths: ["Engineering", "CS", "Management"], highlight: "Strong engineering Russell Group." },
    { id: "nottingham", name: "University of Nottingham", country: "UK", city: "Nottingham", rank: 108, natRank: 18, type: "Public", founded: 1881, website: "nottingham.ac.uk", programs: ["MSc Computer Science", "MSc Data Science", "MSc Management", "MSc Finance", "MSc Engineering"], ielts: 6.5, gre: "Optional", gmat: 600, gpa: "3.0/4.0 (2:1)", tuitionUSD: 3e4, feeNote: "\xA325k/yr", intakes: ["Sep"], deadline: "Rolling", acceptance: 55, scholarship: "Developing Solutions Scholarships", strengths: ["Engineering", "Business", "Pharmacy"], highlight: "Green campus; strong global outlook." },
    { id: "durham", name: "Durham University", country: "UK", city: "Durham", rank: 78, natRank: 11, type: "Public", founded: 1832, website: "durham.ac.uk", programs: ["MSc Computer Science", "MSc Data Science", "MSc Finance", "MBA", "MSc Economics"], ielts: 6.5, gre: "Optional", gmat: 600, gpa: "3.3/4.0 (2:1)", tuitionUSD: 35e3, feeNote: "\xA328k/yr", intakes: ["Sep"], deadline: "Rolling", acceptance: 40, scholarship: "Durham International Scholarships", strengths: ["Business", "Economics", "Sciences"], highlight: "Historic collegiate university, top for finance." },
    { id: "qmul", name: "Queen Mary University of London", country: "UK", city: "London", rank: 145, natRank: 19, type: "Public", founded: 1885, website: "qmul.ac.uk", programs: ["MSc Computer Science", "MSc Data Science & AI", "MSc Big Data", "MSc Finance", "MSc Management"], ielts: 6.5, gre: "Optional", gmat: 600, gpa: "3.0/4.0 (2:1)", tuitionUSD: 32e3, feeNote: "\xA326k/yr", intakes: ["Sep"], deadline: "Rolling", acceptance: 50, scholarship: "Principal's & country awards", strengths: ["CS", "Engineering", "Law"], highlight: "Russell Group in east London." },
    // ───────── Canada ─────────
    {
      id: "toronto",
      name: "University of Toronto",
      country: "Canada",
      city: "Toronto, ON",
      rank: 25,
      natRank: 1,
      type: "Public",
      founded: 1827,
      website: "utoronto.ca",
      programs: ["MSc Computer Science", "MEng", "Master of Management Analytics", "MBA (Rotman)", "MScAC"],
      ielts: 7,
      toefl: 93,
      pte: 65,
      duolingo: 120,
      gre: "Optional",
      gmat: 670,
      gpa: "3.3/4.0 (B+)",
      workEx: "4 yrs (MBA)",
      tuitionUSD: 42e3,
      feeNote: "CAD 58k/yr",
      appFee: "CAD 125",
      scholarship: "Lester B. Pearson (UG), Connaught",
      intakes: ["Fall (Sep)"],
      deadline: "Dec\u2013Jan",
      acceptance: 43,
      intlPct: 28,
      classProfile: "Avg GPA 3.5 \xB7 GRE 320",
      strengths: ["Computer Science", "Medicine", "Business"],
      alumni: "Frederick Banting, Margaret Atwood",
      highlight: "Canada's top-ranked university."
    },
    {
      id: "ubc",
      name: "University of British Columbia",
      country: "Canada",
      city: "Vancouver, BC",
      rank: 38,
      natRank: 2,
      type: "Public",
      founded: 1908,
      website: "ubc.ca",
      programs: ["MSc Computer Science", "MEng", "Master of Data Science", "MBA (Sauder)", "MMOR"],
      ielts: 6.5,
      toefl: 90,
      pte: 65,
      duolingo: 120,
      gre: "Optional",
      gmat: 650,
      gpa: "3.0/4.0 (B+)",
      workEx: "3 yrs (MBA)",
      tuitionUSD: 25e3,
      feeNote: "CAD 9\u201335k/yr",
      appFee: "CAD 168",
      scholarship: "International Major Entrance, Four Year Doctoral",
      intakes: ["Fall (Sep)", "Winter (Jan)"],
      deadline: "Dec\u2013Jan",
      acceptance: 53,
      intlPct: 30,
      classProfile: "Avg GPA 3.4",
      strengths: ["Computer Science", "Business", "Forestry"],
      alumni: "Justin Trudeau, 8 Nobel laureates",
      highlight: "Beautiful campus; strong CS & business."
    },
    {
      id: "mcgill",
      name: "McGill University",
      country: "Canada",
      city: "Montreal, QC",
      rank: 29,
      natRank: 3,
      type: "Public",
      founded: 1821,
      website: "mcgill.ca",
      programs: ["MSc Computer Science", "MMA", "MBA (Desautels)", "MEng", "MSc Finance"],
      ielts: 6.5,
      toefl: 90,
      pte: 65,
      duolingo: 115,
      gre: "Recommended",
      gmat: 650,
      gpa: "3.0/4.0 (B)",
      workEx: "2 yrs (MBA)",
      tuitionUSD: 22e3,
      feeNote: "CAD 28k/yr",
      appFee: "CAD 130",
      scholarship: "McCall MacBain (fully funded), entrance awards",
      intakes: ["Fall (Sep)"],
      deadline: "Jan\u2013Mar",
      acceptance: 46,
      intlPct: 30,
      classProfile: "Avg GPA 3.3",
      strengths: ["Medicine", "Law", "Business"],
      alumni: "William Shatner, 12 Nobel laureates",
      highlight: "Affordable Montreal; high global ranking."
    },
    {
      id: "waterloo",
      name: "University of Waterloo",
      country: "Canada",
      city: "Waterloo, ON",
      rank: 115,
      natRank: 6,
      type: "Public",
      founded: 1957,
      website: "uwaterloo.ca",
      programs: ["MMath Computer Science", "MEng", "Master of Data Science", "MBET", "MSc Quantum"],
      ielts: 7,
      toefl: 90,
      pte: 63,
      duolingo: 120,
      gre: "Optional",
      gmat: 600,
      gpa: "3.0/4.0 (78%+)",
      workEx: null,
      tuitionUSD: 24e3,
      feeNote: "CAD 30k/yr",
      appFee: "CAD 125",
      scholarship: "International Master's Award, GRS",
      intakes: ["Fall (Sep)", "Winter (Jan)"],
      deadline: "Feb 1 (Fall)",
      acceptance: 53,
      intlPct: 35,
      classProfile: "78%+ average",
      strengths: ["Computer Science", "Engineering", "Co-op"],
      alumni: "Mike Lazaridis (BlackBerry)",
      highlight: "Co-op powerhouse; top for CS & engineering."
    },
    {
      id: "alberta",
      name: "University of Alberta",
      country: "Canada",
      city: "Edmonton, AB",
      rank: 96,
      natRank: 5,
      type: "Public",
      founded: 1908,
      website: "ualberta.ca",
      programs: ["MSc Computing Science", "MEng", "MBA", "MSc Petroleum Eng", "MSc Statistics"],
      ielts: 6.5,
      toefl: 90,
      pte: 59,
      duolingo: 110,
      gre: "Optional",
      gmat: 550,
      gpa: "3.0/4.0",
      workEx: null,
      tuitionUSD: 9e3,
      feeNote: "CAD 12k/yr",
      appFee: "CAD 135",
      scholarship: "Graduate Entrance, AGES",
      intakes: ["Fall (Sep)", "Winter (Jan)"],
      deadline: "Rolling",
      acceptance: 58,
      intlPct: 25,
      classProfile: "Avg GPA 3.2",
      strengths: ["AI/ML", "Energy", "Sciences"],
      alumni: "Richard Sutton (RL pioneer)",
      highlight: "Strong AI research; low tuition."
    },
    { id: "mcmaster", name: "McMaster University", country: "Canada", city: "Hamilton, ON", rank: 176, natRank: 4, type: "Public", founded: 1887, website: "mcmaster.ca", programs: ["MSc Computer Science", "MEng", "MBA (DeGroote)", "MSc Data Science", "MSc Engineering"], ielts: 6.5, gre: "Optional", gmat: 600, gpa: "3.0/4.0 (B+)", tuitionUSD: 2e4, feeNote: "CAD 26k/yr", intakes: ["Fall (Sep)"], deadline: "Jan\u2013Feb", acceptance: 45, scholarship: "Graduate scholarships + assistantships", strengths: ["Health Sciences", "Engineering", "Business"], highlight: "Famed for health sciences & research." },
    { id: "montreal", name: "Universit\xE9 de Montr\xE9al", country: "Canada", city: "Montreal, QC", rank: 141, natRank: 5, type: "Public", founded: 1878, website: "umontreal.ca", programs: ["MSc Computer Science", "MSc Data Science", "MSc AI (Mila)", "MBA (HEC)", "MSc Statistics"], ielts: 6.5, gre: "Optional", gmat: 580, gpa: "3.0/4.0 (B)", tuitionUSD: 18e3, feeNote: "CAD 24k/yr", intakes: ["Fall (Sep)"], deadline: "Feb 1", acceptance: 50, scholarship: "Exemption scholarships", strengths: ["AI/Deep Learning (Mila)", "Medicine", "Statistics"], highlight: "Home of Yoshua Bengio's Mila AI institute." },
    { id: "ottawa", name: "University of Ottawa", country: "Canada", city: "Ottawa, ON", rank: 189, natRank: 7, type: "Public", founded: 1848, website: "uottawa.ca", programs: ["MSc Computer Science", "MEng", "MBA (Telfer)", "MSc Data Science", "MSc Eng Mgmt"], ielts: 6.5, gre: "Optional", gmat: 550, gpa: "3.0/4.0 (B)", tuitionUSD: 17e3, feeNote: "CAD 23k/yr", intakes: ["Fall (Sep)", "Winter (Jan)"], deadline: "Rolling", acceptance: 55, scholarship: "Admission scholarships", strengths: ["CS", "Engineering", "Public Admin"], highlight: "Bilingual capital-city university." },
    { id: "calgary", name: "University of Calgary", country: "Canada", city: "Calgary, AB", rank: 182, natRank: 8, type: "Public", founded: 1966, website: "ucalgary.ca", programs: ["MSc Computer Science", "MEng", "MBA (Haskayne)", "MSc Data Science", "MSc Energy"], ielts: 6.5, gre: "Optional", gmat: 550, gpa: "3.0/4.0 (B)", tuitionUSD: 16e3, feeNote: "CAD 22k/yr", intakes: ["Fall (Sep)", "Winter (Jan)"], deadline: "Rolling", acceptance: 56, scholarship: "Graduate awards", strengths: ["Energy", "Engineering", "CS"], highlight: "Strong energy & engineering research." },
    { id: "western", name: "Western University", country: "Canada", city: "London, ON", rank: 114, natRank: 8, type: "Public", founded: 1878, website: "uwo.ca", programs: ["MSc Computer Science", "MEng", "MBA (Ivey)", "MSc Data Analytics", "MSc Engineering"], ielts: 6.5, gre: "Optional", gmat: 650, gpa: "3.0/4.0 (B+)", tuitionUSD: 22e3, feeNote: "CAD 30k/yr", intakes: ["Fall (Sep)"], deadline: "Jan\u2013Mar", acceptance: 45, scholarship: "Western Graduate Research Scholarship", strengths: ["Business (Ivey)", "Engineering", "Medicine"], highlight: "Home of the top-ranked Ivey Business School." },
    { id: "queensu", name: "Queen's University", country: "Canada", city: "Kingston, ON", rank: 209, natRank: 6, type: "Public", founded: 1841, website: "queensu.ca", programs: ["MSc Computing", "MEng", "MBA (Smith)", "Master of Management Analytics", "MSc Engineering"], ielts: 6.5, gre: "Optional", gmat: 630, gpa: "3.0/4.0 (B+)", tuitionUSD: 21e3, feeNote: "CAD 28k/yr", intakes: ["Fall (Sep)"], deadline: "Feb", acceptance: 42, scholarship: "Graduate awards", strengths: ["Business (Smith)", "Engineering", "Computing"], highlight: "Prestigious; top business analytics programs." },
    { id: "sfu", name: "Simon Fraser University", country: "Canada", city: "Burnaby, BC", rank: 318, natRank: 11, type: "Public", founded: 1965, website: "sfu.ca", programs: ["MSc Computing Science", "MEng", "Master of Data Science", "MBA", "MSc Engineering"], ielts: 6.5, gre: "Optional", gmat: 550, gpa: "3.0/4.0 (B)", tuitionUSD: 15e3, feeNote: "CAD 20k/yr", intakes: ["Fall (Sep)", "Spring (Jan)"], deadline: "Rolling", acceptance: 55, scholarship: "Graduate fellowships", strengths: ["Computing", "Interactive Arts", "Business"], highlight: "Strong CS & co-op near Vancouver." },
    { id: "dalhousie", name: "Dalhousie University", country: "Canada", city: "Halifax, NS", rank: 298, natRank: 12, type: "Public", founded: 1818, website: "dal.ca", programs: ["MSc Computer Science", "MEng", "MBA", "Master of Data Analytics", "MSc Engineering"], ielts: 6.5, gre: "Optional", gmat: 550, gpa: "3.0/4.0 (B)", tuitionUSD: 14e3, feeNote: "CAD 19k/yr", intakes: ["Fall (Sep)", "Winter (Jan)"], deadline: "Rolling", acceptance: 58, scholarship: "Graduate scholarships", strengths: ["Ocean Sciences", "CS", "Engineering"], highlight: "Atlantic Canada's leading research university." },
    { id: "victoria", name: "University of Victoria", country: "Canada", city: "Victoria, BC", rank: 334, natRank: 13, type: "Public", founded: 1963, website: "uvic.ca", programs: ["MSc Computer Science", "MEng", "MBA", "MSc Data Science", "MSc Engineering"], ielts: 6.5, gre: "Optional", gmat: 550, gpa: "3.0/4.0 (B)", tuitionUSD: 15e3, feeNote: "CAD 20k/yr", intakes: ["Fall (Sep)"], deadline: "Rolling", acceptance: 55, scholarship: "UVic graduate awards", strengths: ["CS", "Engineering", "Co-op"], highlight: "Co-op focus on Canada's west coast." },
    { id: "carleton", name: "Carleton University", country: "Canada", city: "Ottawa, ON", rank: 626, natRank: 16, type: "Public", founded: 1942, website: "carleton.ca", programs: ["MSc Computer Science", "MEng", "MBA (Sprott)", "MSc Data Science", "MEng Tech Innovation"], ielts: 6.5, gre: "Optional", gmat: 550, gpa: "3.0/4.0 (B)", tuitionUSD: 15e3, feeNote: "CAD 20k/yr", intakes: ["Fall (Sep)", "Winter (Jan)"], deadline: "Rolling", acceptance: 58, scholarship: "Graduate funding packages", strengths: ["Engineering", "CS", "Public Affairs"], highlight: "Strong tech links in the capital." },
    { id: "concordia", name: "Concordia University", country: "Canada", city: "Montreal, QC", rank: 549, natRank: 18, type: "Public", founded: 1974, website: "concordia.ca", programs: ["MEng Computer Science", "MEng", "MBA (JMSB)", "MSc Data Science", "MEng Quality Systems"], ielts: 6.5, gre: "Optional", gmat: 550, gpa: "3.0/4.0 (B)", tuitionUSD: 15e3, feeNote: "CAD 20k/yr", intakes: ["Fall (Sep)", "Winter (Jan)"], deadline: "Rolling", acceptance: 60, scholarship: "Entrance awards", strengths: ["Engineering", "CS", "Fine Arts"], highlight: "Affordable, very international, in Montreal." },
    { id: "yorku", name: "York University", country: "Canada", city: "Toronto, ON", rank: 386, natRank: 17, type: "Public", founded: 1959, website: "yorku.ca", programs: ["MSc Computer Science", "MBA (Schulich)", "Master of Business Analytics", "MEng", "MSc Data Science"], ielts: 6.5, gre: "Optional", gmat: 620, gpa: "3.0/4.0 (B)", tuitionUSD: 17e3, feeNote: "CAD 23k/yr", intakes: ["Fall (Sep)"], deadline: "Rolling", acceptance: 55, scholarship: "Graduate scholarships", strengths: ["Business (Schulich)", "Law", "CS"], highlight: "Large Toronto university; top Schulich MBA." },
    // ───────── Australia ─────────
    {
      id: "melbourne",
      name: "University of Melbourne",
      country: "Australia",
      city: "Melbourne",
      rank: 13,
      natRank: 1,
      type: "Public",
      founded: 1853,
      website: "unimelb.edu.au",
      programs: ["Master of Computer Science", "Master of Data Science", "MBA", "Master of IT", "Master of Eng"],
      ielts: 6.5,
      toefl: 79,
      pte: 58,
      duolingo: 115,
      gre: "Optional",
      gmat: 650,
      gpa: "3.0/4.0",
      workEx: "2 yrs (MBA)",
      tuitionUSD: 32e3,
      feeNote: "AUD 48k/yr",
      appFee: "AUD 100",
      scholarship: "Graduate Research, Melbourne International",
      intakes: ["Feb", "Jul"],
      deadline: "Oct/Apr (rounds)",
      acceptance: 70,
      intlPct: 45,
      classProfile: "Avg GPA 3.0+",
      strengths: ["Research", "Computer Science", "Business"],
      alumni: "4 Australian PMs",
      highlight: "Australia's #1 university."
    },
    {
      id: "sydney",
      name: "University of Sydney",
      country: "Australia",
      city: "Sydney",
      rank: 18,
      natRank: 2,
      type: "Public",
      founded: 1850,
      website: "sydney.edu.au",
      programs: ["Master of IT", "Master of Data Science", "MBA", "Master of Commerce", "Master of Eng"],
      ielts: 6.5,
      toefl: 85,
      pte: 61,
      duolingo: 115,
      gre: "Optional",
      gmat: 600,
      gpa: "3.0/4.0",
      workEx: null,
      tuitionUSD: 33e3,
      feeNote: "AUD 50k/yr",
      appFee: "AUD 125",
      scholarship: "Sydney Scholars, country awards",
      intakes: ["Feb", "Aug"],
      deadline: "Rolling",
      acceptance: 30,
      intlPct: 46,
      classProfile: "Credit average (65%+)",
      strengths: ["Business", "Engineering", "Medicine"],
      alumni: "5 Australian PMs",
      highlight: "Prestigious; strong graduate employability."
    },
    {
      id: "unsw",
      name: "UNSW Sydney",
      country: "Australia",
      city: "Sydney",
      rank: 19,
      natRank: 3,
      type: "Public",
      founded: 1949,
      website: "unsw.edu.au",
      programs: ["Master of IT", "Master of Data Science & Decisions", "MBA (AGSM)", "Master of Eng", "Master of Finance"],
      ielts: 6.5,
      toefl: 90,
      pte: 64,
      duolingo: 115,
      gre: "Optional",
      gmat: 600,
      gpa: "3.0/4.0",
      workEx: "2 yrs (MBA)",
      tuitionUSD: 31e3,
      feeNote: "AUD 47k/yr",
      appFee: "Free",
      scholarship: "Scientia, country scholarships",
      intakes: ["Feb", "Jun", "Sep"],
      deadline: "Rolling (3 terms)",
      acceptance: 30,
      intlPct: 48,
      classProfile: "Credit average (65%+)",
      strengths: ["Engineering", "Business", "Quantum"],
      alumni: "Australian tech founders",
      highlight: "Three intakes/yr; strong engineering."
    },
    {
      id: "anu",
      name: "Australian National University",
      country: "Australia",
      city: "Canberra",
      rank: 30,
      natRank: 4,
      type: "Public",
      founded: 1946,
      website: "anu.edu.au",
      programs: ["Master of Computing", "Master of Machine Learning & CV", "Master of Eng", "Master of Finance"],
      ielts: 6.5,
      toefl: 80,
      pte: 64,
      duolingo: 115,
      gre: "Optional",
      gmat: 600,
      gpa: "3.0/4.0",
      workEx: null,
      tuitionUSD: 31e3,
      feeNote: "AUD 47k/yr",
      appFee: "Free",
      scholarship: "ANU Chancellor's, country awards",
      intakes: ["Feb", "Jul"],
      deadline: "Rolling",
      acceptance: 35,
      intlPct: 40,
      classProfile: "Avg GPA 3.0+",
      strengths: ["Research", "Computing", "Policy"],
      alumni: "6 Nobel laureates",
      highlight: "Research-intensive national university."
    },
    {
      id: "monash",
      name: "Monash University",
      country: "Australia",
      city: "Melbourne",
      rank: 37,
      natRank: 5,
      type: "Public",
      founded: 1958,
      website: "monash.edu",
      programs: ["Master of IT", "Master of Data Science", "MBA", "Master of Eng", "Master of Business"],
      ielts: 6.5,
      toefl: 79,
      pte: 58,
      duolingo: 110,
      gre: "Optional",
      gmat: 580,
      gpa: "3.0/4.0",
      workEx: null,
      tuitionUSD: 3e4,
      feeNote: "AUD 45k/yr",
      appFee: "Free",
      scholarship: "Monash International Merit",
      intakes: ["Feb", "Jul"],
      deadline: "Rolling",
      acceptance: 60,
      intlPct: 40,
      classProfile: "Credit average",
      strengths: ["Pharmacy", "Engineering", "Business"],
      alumni: "Tim Costello",
      highlight: "Large, internationally diverse campus."
    },
    { id: "uq", name: "University of Queensland", country: "Australia", city: "Brisbane", rank: 40, natRank: 6, type: "Public", founded: 1909, website: "uq.edu.au", programs: ["Master of Computer Science", "Master of Data Science", "MBA", "Master of Eng", "Master of Business Analytics"], ielts: 6.5, gre: "Optional", gmat: 600, gpa: "3.0/4.0", tuitionUSD: 3e4, feeNote: "AUD 46k/yr", intakes: ["Feb", "Jul"], deadline: "Rolling", acceptance: 50, scholarship: "UQ International Scholarships", strengths: ["Sciences", "Engineering", "Business"], highlight: "Group of Eight; strong research output." },
    { id: "adelaide", name: "University of Adelaide", country: "Australia", city: "Adelaide", rank: 82, natRank: 8, type: "Public", founded: 1874, website: "adelaide.edu.au", programs: ["Master of Computer Science", "Master of Data Science", "MBA", "Master of Eng", "Master of Finance"], ielts: 6.5, gre: "Optional", gmat: 550, gpa: "3.0/4.0", tuitionUSD: 28e3, feeNote: "AUD 44k/yr", intakes: ["Feb", "Jul"], deadline: "Rolling", acceptance: 60, scholarship: "Global Citizens Scholarship", strengths: ["Wine/Agri", "Engineering", "CS"], highlight: "Group of Eight; regional migration points." },
    { id: "uwa", name: "University of Western Australia", country: "Australia", city: "Perth", rank: 77, natRank: 7, type: "Public", founded: 1911, website: "uwa.edu.au", programs: ["Master of IT", "Master of Data Science", "MBA", "Master of Eng", "Master of Commerce"], ielts: 6.5, gre: "Optional", gmat: 550, gpa: "3.0/4.0", tuitionUSD: 28e3, feeNote: "AUD 44k/yr", intakes: ["Feb", "Jul"], deadline: "Rolling", acceptance: 60, scholarship: "Global Excellence Scholarships", strengths: ["Mining", "Sciences", "Business"], highlight: "Group of Eight in resource-rich Perth." },
    { id: "uts", name: "University of Technology Sydney (UTS)", country: "Australia", city: "Sydney", rank: 88, natRank: 9, type: "Public", founded: 1988, website: "uts.edu.au", programs: ["Master of IT", "Master of Data Science", "MBA", "Master of Eng", "Master of Analytics"], ielts: 6.5, gre: "Optional", gmat: 550, gpa: "3.0/4.0", tuitionUSD: 28e3, feeNote: "AUD 44k/yr", intakes: ["Feb", "Jul"], deadline: "Rolling", acceptance: 60, scholarship: "UTS International Scholarships", strengths: ["IT", "Engineering", "Design"], highlight: "Industry-focused, modern Sydney campus." },
    { id: "wollongong", name: "University of Wollongong", country: "Australia", city: "Wollongong", rank: 167, natRank: 11, type: "Public", founded: 1951, website: "uow.edu.au", programs: ["Master of CS", "Master of Data Analytics", "MBA", "Master of Eng", "Master of IT"], ielts: 6.5, gre: "Optional", gmat: 550, gpa: "3.0/4.0", tuitionUSD: 24e3, feeNote: "AUD 38k/yr", intakes: ["Feb", "Jul"], deadline: "Rolling", acceptance: 65, scholarship: "UOW International Scholarships", strengths: ["Engineering", "IT", "Business"], highlight: "Affordable, strong engineering, near Sydney." },
    { id: "rmit", name: "RMIT University", country: "Australia", city: "Melbourne", rank: 123, natRank: 12, type: "Public", founded: 1887, website: "rmit.edu.au", programs: ["Master of IT", "Master of Data Science", "MBA", "Master of Eng", "Master of Analytics"], ielts: 6.5, gre: "Optional", gmat: 550, gpa: "3.0/4.0", tuitionUSD: 25e3, feeNote: "AUD 40k/yr", intakes: ["Feb", "Jul"], deadline: "Rolling", acceptance: 60, scholarship: "RMIT International Scholarships", strengths: ["Design", "IT", "Engineering"], highlight: "Industry & design focus in central Melbourne." },
    { id: "macquarie", name: "Macquarie University", country: "Australia", city: "Sydney", rank: 130, natRank: 10, type: "Public", founded: 1964, website: "mq.edu.au", programs: ["Master of IT", "Master of Data Science", "MBA", "Master of Eng", "Master of Applied Finance"], ielts: 6.5, gre: "Optional", gmat: 550, gpa: "3.0/4.0", tuitionUSD: 26e3, feeNote: "AUD 42k/yr", intakes: ["Feb", "Jul"], deadline: "Rolling", acceptance: 62, scholarship: "Vice-Chancellor's Scholarships", strengths: ["Finance/Actuarial", "IT", "Linguistics"], highlight: "Strong finance & tech in northern Sydney." },
    { id: "deakin", name: "Deakin University", country: "Australia", city: "Melbourne", rank: 197, natRank: 14, type: "Public", founded: 1974, website: "deakin.edu.au", programs: ["Master of IT", "Master of Data Science", "MBA", "Master of Eng", "Master of Business Analytics"], ielts: 6.5, gre: "Optional", gmat: 550, gpa: "3.0/4.0", tuitionUSD: 24e3, feeNote: "AUD 38k/yr", intakes: ["Mar", "Jul", "Nov"], deadline: "Rolling", acceptance: 65, scholarship: "Deakin Vice-Chancellor's Scholarship", strengths: ["IT", "Health", "Business"], highlight: "Three intakes; strong cloud/online options." },
    { id: "qut", name: "Queensland University of Technology", country: "Australia", city: "Brisbane", rank: 189, natRank: 13, type: "Public", founded: 1989, website: "qut.edu.au", programs: ["Master of IT", "Master of Data Analytics", "MBA", "Master of Eng", "Master of Business"], ielts: 6.5, gre: "Optional", gmat: 550, gpa: "3.0/4.0", tuitionUSD: 24e3, feeNote: "AUD 38k/yr", intakes: ["Feb", "Jul"], deadline: "Rolling", acceptance: 63, scholarship: "QUT International Merit Scholarships", strengths: ["IT", "Engineering", "Creative"], highlight: "'University for the real world' in Brisbane." },
    { id: "curtin", name: "Curtin University", country: "Australia", city: "Perth", rank: 174, natRank: 15, type: "Public", founded: 1966, website: "curtin.edu.au", programs: ["Master of IT", "Master of Data Science", "MBA", "Master of Eng", "Master of Commerce"], ielts: 6.5, gre: "Optional", gmat: 550, gpa: "3.0/4.0", tuitionUSD: 23e3, feeNote: "AUD 37k/yr", intakes: ["Feb", "Jul"], deadline: "Rolling", acceptance: 65, scholarship: "Curtin International Scholarships", strengths: ["Mining", "Engineering", "Business"], highlight: "Largest WA university; mining & resources." },
    // ───────── Germany (low/no tuition) ─────────
    {
      id: "tum",
      name: "Technical University of Munich (TUM)",
      country: "Germany",
      city: "Munich",
      rank: 22,
      natRank: 1,
      type: "Public",
      founded: 1868,
      website: "tum.de",
      programs: ["MSc Informatics", "MSc Data Engineering & Analytics", "MSc Management", "MSc Mechanical Eng", "MSc Robotics"],
      ielts: 6.5,
      toefl: 88,
      pte: 59,
      duolingo: 110,
      gre: "Required (many)",
      gmat: 650,
      gpa: "2.5/4.0 (German)",
      workEx: null,
      tuitionUSD: 350,
      feeNote: "\u2248\u20AC150/sem (no tuition)",
      appFee: "Free",
      scholarship: "Deutschlandstipendium (\u20AC300/mo), DAAD",
      intakes: ["Winter (Oct)", "Summer (Apr)"],
      deadline: "May 31 (Winter)",
      acceptance: 8,
      intlPct: 32,
      classProfile: "Strong quantitative background",
      strengths: ["Engineering", "Informatics", "Robotics"],
      alumni: "Rudolf Diesel, 18 Nobel laureates",
      highlight: "Top EU tech school; essentially tuition-free."
    },
    {
      id: "rwth",
      name: "RWTH Aachen University",
      country: "Germany",
      city: "Aachen",
      rank: 99,
      natRank: 5,
      type: "Public",
      founded: 1870,
      website: "rwth-aachen.de",
      programs: ["MSc Computer Science", "MSc Data Science", "MSc Mechanical Eng", "MSc Automotive Eng", "MSc Robotics"],
      ielts: 6.5,
      toefl: 90,
      pte: 59,
      duolingo: 110,
      gre: "Recommended",
      gmat: null,
      gpa: "2.5/4.0",
      workEx: null,
      tuitionUSD: 350,
      feeNote: "\u2248\u20AC300/sem (no tuition)",
      appFee: "Free",
      scholarship: "DAAD, Deutschlandstipendium",
      intakes: ["Winter (Oct)", "Summer (Apr)"],
      deadline: "Mar 1 (Winter)",
      acceptance: 10,
      intlPct: 25,
      classProfile: "Strong engineering background",
      strengths: ["Mechanical Eng", "Automotive", "CS"],
      alumni: "Industry engineers",
      highlight: "Germany's top engineering university."
    },
    {
      id: "tuberlin",
      name: "Technical University of Berlin",
      country: "Germany",
      city: "Berlin",
      rank: 154,
      natRank: 7,
      type: "Public",
      founded: 1879,
      website: "tu.berlin",
      programs: ["MSc Computer Science", "MSc Data Analytics", "MSc ICT Innovation", "MSc Eng", "MSc Urban Mgmt"],
      ielts: 6.5,
      toefl: 87,
      pte: 59,
      duolingo: 110,
      gre: "Optional",
      gmat: null,
      gpa: "2.5/4.0",
      workEx: null,
      tuitionUSD: 350,
      feeNote: "\u2248\u20AC310/sem (no tuition)",
      appFee: "Free",
      scholarship: "DAAD, EIT Digital",
      intakes: ["Winter (Oct)", "Summer (Apr)"],
      deadline: "Mar 15 (Winter)",
      acceptance: 15,
      intlPct: 28,
      classProfile: "Relevant bachelor's",
      strengths: ["Engineering", "CS", "Sustainability"],
      alumni: "Carl Bosch, Wernher von Braun",
      highlight: "Berlin's startup scene; tuition-free."
    },
    { id: "lmu", name: "Ludwig Maximilian University of Munich (LMU)", country: "Germany", city: "Munich", rank: 59, natRank: 2, type: "Public", founded: 1472, website: "lmu.de", programs: ["MSc Computer Science", "MSc Data Science", "MSc Statistics", "MSc Economics", "MSc Management"], ielts: 6.5, gre: "Recommended", gmat: null, gpa: "2.5/4.0", tuitionUSD: 350, feeNote: "\u2248\u20AC150/sem (no tuition)", intakes: ["Winter (Oct)"], deadline: "May 31", acceptance: 15, scholarship: "DAAD, Deutschlandstipendium", strengths: ["Statistics", "Economics", "Sciences"], highlight: "Germany's top comprehensive university." },
    { id: "heidelberg", name: "Heidelberg University", country: "Germany", city: "Heidelberg", rank: 84, natRank: 3, type: "Public", founded: 1386, website: "uni-heidelberg.de", programs: ["MSc Computer Science", "MSc Data & Computer Science", "MSc Physics", "MSc Scientific Computing", "MSc Economics"], ielts: 6.5, gre: "Recommended", gmat: null, gpa: "2.5/4.0", tuitionUSD: 3e3, feeNote: "\u2248\u20AC1,500/sem (BW)", intakes: ["Winter (Oct)", "Summer (Apr)"], deadline: "Varies", acceptance: 18, scholarship: "DAAD, HAI scholarships", strengths: ["Medicine", "Sciences", "Computing"], highlight: "Germany's oldest university; research elite." },
    { id: "kit", name: "Karlsruhe Institute of Technology (KIT)", country: "Germany", city: "Karlsruhe", rank: 102, natRank: 6, type: "Public", founded: 2009, website: "kit.edu", programs: ["MSc Computer Science", "MSc Data Science", "MSc Mechanical Eng", "MSc Electrical Eng", "MSc Information Eng"], ielts: 6.5, gre: "Recommended", gmat: null, gpa: "2.5/4.0", tuitionUSD: 3e3, feeNote: "\u2248\u20AC1,500/sem (BW)", intakes: ["Winter (Oct)", "Summer (Apr)"], deadline: "Varies", acceptance: 20, scholarship: "DAAD, KIT scholarships", strengths: ["Engineering", "CS", "Physics"], highlight: "Germany's 'MIT'; top for engineering & CS." },
    { id: "freiburg", name: "University of Freiburg", country: "Germany", city: "Freiburg", rank: 192, natRank: 9, type: "Public", founded: 1457, website: "uni-freiburg.de", programs: ["MSc Computer Science", "MSc Embedded Systems", "MSc Microsystems Eng", "MSc Sustainability", "MSc Economics"], ielts: 6.5, gre: "Optional", gmat: null, gpa: "2.5/4.0", tuitionUSD: 3e3, feeNote: "\u2248\u20AC1,500/sem (BW)", intakes: ["Winter (Oct)", "Summer (Apr)"], deadline: "Varies", acceptance: 25, scholarship: "DAAD, Deutschlandstipendium", strengths: ["Microsystems", "Sustainability", "CS"], highlight: "Historic university in the Black Forest." },
    { id: "humboldt", name: "Humboldt University of Berlin", country: "Germany", city: "Berlin", rank: 120, natRank: 5, type: "Public", founded: 1810, website: "hu-berlin.de", programs: ["MSc Computer Science", "MSc Statistics", "MSc Economics", "MSc Data Science", "MSc Mathematics"], ielts: 6.5, gre: "Optional", gmat: null, gpa: "2.5/4.0", tuitionUSD: 350, feeNote: "\u2248\u20AC315/sem (no tuition)", intakes: ["Winter (Oct)"], deadline: "Varies", acceptance: 20, scholarship: "DAAD, Elsa Neumann", strengths: ["Statistics", "Economics", "Humanities"], highlight: "Berlin's historic research university." },
    { id: "stuttgart", name: "University of Stuttgart", country: "Germany", city: "Stuttgart", rank: 312, natRank: 11, type: "Public", founded: 1829, website: "uni-stuttgart.de", programs: ["MSc Computer Science", "MSc INFOTECH", "MSc Automotive Eng", "MSc Data Science", "MSc Mechanical Eng"], ielts: 6.5, gre: "Recommended", gmat: null, gpa: "2.5/4.0", tuitionUSD: 3e3, feeNote: "\u2248\u20AC1,500/sem (BW)", intakes: ["Winter (Oct)", "Summer (Apr)"], deadline: "Varies", acceptance: 25, scholarship: "DAAD, STIBET", strengths: ["Automotive", "Aerospace", "CS"], highlight: "In the heart of Germany's auto industry." },
    { id: "darmstadt", name: "Technical University of Darmstadt", country: "Germany", city: "Darmstadt", rank: 312, natRank: 12, type: "Public", founded: 1877, website: "tu-darmstadt.de", programs: ["MSc Computer Science", "MSc Data & Discovery", "MSc Electrical Eng", "MSc Mechanical Eng", "MSc AI"], ielts: 6.5, gre: "Optional", gmat: null, gpa: "2.5/4.0", tuitionUSD: 350, feeNote: "\u2248\u20AC270/sem (no tuition)", intakes: ["Winter (Oct)", "Summer (Apr)"], deadline: "Varies", acceptance: 22, scholarship: "DAAD, Deutschlandstipendium", strengths: ["CS/AI", "Electrical Eng", "Mechatronics"], highlight: "Top for CS & AI; tuition-free." },
    // ───────── Ireland, NZ, Singapore, Netherlands ─────────
    {
      id: "tcd",
      name: "Trinity College Dublin",
      country: "Ireland",
      city: "Dublin",
      rank: 87,
      natRank: 1,
      type: "Public",
      founded: 1592,
      website: "tcd.ie",
      programs: ["MSc Computer Science", "MSc Data Science", "MSc Finance", "MSc Management", "MSc AI"],
      ielts: 6.5,
      toefl: 88,
      pte: 63,
      duolingo: 115,
      gre: "Optional",
      gmat: 600,
      gpa: "3.0/4.0 (2:1)",
      workEx: null,
      tuitionUSD: 28e3,
      feeNote: "\u20AC25\u201330k/yr",
      appFee: "\u20AC55",
      scholarship: "Global Excellence, country awards",
      intakes: ["Sep"],
      deadline: "Rolling (apply by Jun)",
      acceptance: 33,
      intlPct: 30,
      classProfile: "2:1 honours equivalent",
      strengths: ["CS", "Literature", "Business"],
      alumni: "Oscar Wilde, Samuel Beckett",
      highlight: "Ireland's #1; 2-yr post-study work visa."
    },
    {
      id: "ucd",
      name: "University College Dublin",
      country: "Ireland",
      city: "Dublin",
      rank: 126,
      natRank: 2,
      type: "Public",
      founded: 1854,
      website: "ucd.ie",
      programs: ["MSc Computer Science", "MSc Business Analytics", "MBA (Smurfit)", "MSc Finance", "MSc Data Science"],
      ielts: 6.5,
      toefl: 90,
      pte: 63,
      duolingo: 115,
      gre: "Optional",
      gmat: 600,
      gpa: "3.0/4.0 (2:1)",
      workEx: "3 yrs (MBA)",
      tuitionUSD: 27e3,
      feeNote: "\u20AC24\u201329k/yr",
      appFee: "\u20AC50",
      scholarship: "UCD Global Excellence",
      intakes: ["Sep", "Jan"],
      deadline: "Rolling",
      acceptance: 40,
      intlPct: 28,
      classProfile: "2:1 honours equivalent",
      strengths: ["Business", "Agriculture", "CS"],
      alumni: "James Joyce, 3 Irish Presidents",
      highlight: "Strong business school; EU tech hub."
    },
    {
      id: "auckland",
      name: "University of Auckland",
      country: "New Zealand",
      city: "Auckland",
      rank: 65,
      natRank: 1,
      type: "Public",
      founded: 1883,
      website: "auckland.ac.nz",
      programs: ["Master of IT", "Master of Data Science", "MBA", "Master of Eng", "Master of Business"],
      ielts: 6.5,
      toefl: 90,
      pte: 58,
      duolingo: 110,
      gre: "Optional",
      gmat: 550,
      gpa: "3.0/4.0 (B)",
      workEx: null,
      tuitionUSD: 28e3,
      feeNote: "NZD 45k/yr",
      appFee: "NZD 105",
      scholarship: "International Student Excellence",
      intakes: ["Mar", "Jul"],
      deadline: "Rolling",
      acceptance: 46,
      intlPct: 30,
      classProfile: "B average",
      strengths: ["Research", "Business", "Engineering"],
      alumni: "3 NZ PMs",
      highlight: "NZ's #1; welcoming post-study work rights."
    },
    {
      id: "nus",
      name: "National University of Singapore (NUS)",
      country: "Singapore",
      city: "Singapore",
      rank: 8,
      natRank: 1,
      type: "Public",
      founded: 1905,
      website: "nus.edu.sg",
      programs: ["MComp (CS)", "MSc Data Science & ML", "MBA", "MSc Business Analytics", "MSc Finance"],
      ielts: 6.5,
      toefl: 92,
      pte: 65,
      duolingo: 115,
      gre: "Recommended",
      gmat: 670,
      gpa: "3.3/4.0",
      workEx: "2 yrs (MBA)",
      tuitionUSD: 3e4,
      feeNote: "SGD 40\u201355k/yr",
      appFee: "SGD 100",
      scholarship: "NUS Graduate, ASEAN awards",
      intakes: ["Aug (Fall)", "Jan"],
      deadline: "Nov\u2013Mar",
      acceptance: 16,
      intlPct: 30,
      classProfile: "Avg GRE 320 \xB7 GPA 3.5",
      strengths: ["Computer Science", "Business", "Engineering"],
      alumni: "4 Singapore PMs",
      highlight: "Asia's #1; global recognition, work hub."
    },
    {
      id: "tudelft",
      name: "Delft University of Technology",
      country: "Netherlands",
      city: "Delft",
      rank: 49,
      natRank: 1,
      type: "Public",
      founded: 1842,
      website: "tudelft.nl",
      programs: ["MSc Computer Science", "MSc Data Science", "MSc Aerospace Eng", "MSc Robotics", "MSc Eng"],
      ielts: 6.5,
      toefl: 90,
      pte: 59,
      duolingo: 115,
      gre: "Recommended",
      gmat: null,
      gpa: "3.0/4.0",
      workEx: null,
      tuitionUSD: 22e3,
      feeNote: "\u20AC18\u201320k/yr",
      appFee: "\u20AC100",
      scholarship: "Justus & Louise van Effen, Holland Scholarship",
      intakes: ["Sep (Fall)"],
      deadline: "Apr 1 / Jan 15",
      acceptance: 35,
      intlPct: 35,
      classProfile: "Strong technical background",
      strengths: ["Aerospace", "CS", "Civil Eng"],
      alumni: "Aerospace & tech leaders",
      highlight: "Europe's top tech university; English-taught."
    },
    // Ireland
    { id: "galway", name: "University of Galway", country: "Ireland", city: "Galway", rank: 289, natRank: 3, type: "Public", founded: 1845, website: "universityofgalway.ie", programs: ["MSc Computer Science", "MSc Data Analytics", "MSc AI", "MSc Software Design", "MSc Finance"], ielts: 6.5, gre: "Optional", gmat: 580, gpa: "3.0/4.0 (2:1)", tuitionUSD: 24e3, feeNote: "\u20AC22\u201326k/yr", intakes: ["Sep"], deadline: "Rolling", acceptance: 45, scholarship: "Galway International Scholarships", strengths: ["Medical Devices", "CS", "Data"], highlight: "Strong medtech & data science on the west coast." },
    { id: "ucc", name: "University College Cork", country: "Ireland", city: "Cork", rank: 273, natRank: 4, type: "Public", founded: 1845, website: "ucc.ie", programs: ["MSc Computer Science", "MSc Data Science & Analytics", "MSc AI", "MSc Finance", "MSc Management"], ielts: 6.5, gre: "Optional", gmat: 580, gpa: "3.0/4.0 (2:1)", tuitionUSD: 24e3, feeNote: "\u20AC22\u201326k/yr", intakes: ["Sep"], deadline: "Rolling", acceptance: 45, scholarship: "UCC Excellence Scholarships", strengths: ["Pharma", "CS", "Business"], highlight: "Top Irish university for pharma & tech." },
    { id: "dcu", name: "Dublin City University", country: "Ireland", city: "Dublin", rank: 421, natRank: 5, type: "Public", founded: 1989, website: "dcu.ie", programs: ["MSc Computing", "MSc Data Analytics", "MSc AI", "MBA", "MSc Finance"], ielts: 6.5, gre: "Optional", gmat: 550, gpa: "3.0/4.0 (2:1)", tuitionUSD: 22e3, feeNote: "\u20AC20\u201324k/yr", intakes: ["Sep", "Jan"], deadline: "Rolling", acceptance: 50, scholarship: "DCU International Scholarships", strengths: ["Computing", "Business", "Communications"], highlight: "Industry-focused, two intakes, in Dublin." },
    { id: "ul", name: "University of Limerick", country: "Ireland", city: "Limerick", rank: 461, natRank: 6, type: "Public", founded: 1972, website: "ul.ie", programs: ["MSc Computer Science", "MSc Data Analytics", "MSc AI", "MSc Software Eng", "MSc Finance"], ielts: 6.5, gre: "Optional", gmat: 550, gpa: "3.0/4.0 (2:1)", tuitionUSD: 22e3, feeNote: "\u20AC20\u201324k/yr", intakes: ["Sep"], deadline: "Rolling", acceptance: 52, scholarship: "UL Global Scholarships", strengths: ["Co-op", "CS", "Engineering"], highlight: "Famous co-op program in Ireland." },
    // New Zealand
    { id: "otago", name: "University of Otago", country: "New Zealand", city: "Dunedin", rank: 214, natRank: 2, type: "Public", founded: 1869, website: "otago.ac.nz", programs: ["Master of Science (CS)", "Master of Data Science", "MBA", "Master of Finance", "Master of Health Sciences"], ielts: 6.5, gre: "Optional", gmat: 550, gpa: "3.0/4.0 (B)", tuitionUSD: 26e3, feeNote: "NZD 42k/yr", intakes: ["Feb", "Jul"], deadline: "Rolling", acceptance: 50, scholarship: "Otago International Scholarships", strengths: ["Health Sciences", "Sciences", "Business"], highlight: "NZ's oldest university; strong health sciences." },
    { id: "vuw", name: "Victoria University of Wellington", country: "New Zealand", city: "Wellington", rank: 244, natRank: 3, type: "Public", founded: 1897, website: "wgtn.ac.nz", programs: ["Master of CS", "Master of Data Science", "MBA", "Master of Engineering", "Master of Finance"], ielts: 6.5, gre: "Optional", gmat: 550, gpa: "3.0/4.0 (B)", tuitionUSD: 26e3, feeNote: "NZD 42k/yr", intakes: ["Mar", "Jul"], deadline: "Rolling", acceptance: 52, scholarship: "Wellington International Excellence", strengths: ["Law", "CS", "Public Policy"], highlight: "Capital-city university; strong CS & law." },
    { id: "canterbury", name: "University of Canterbury", country: "New Zealand", city: "Christchurch", rank: 261, natRank: 4, type: "Public", founded: 1873, website: "canterbury.ac.nz", programs: ["Master of CS", "Master of Data Science", "MBA", "Master of Engineering", "Master of Business"], ielts: 6.5, gre: "Optional", gmat: 550, gpa: "3.0/4.0 (B)", tuitionUSD: 25e3, feeNote: "NZD 40k/yr", intakes: ["Feb", "Jul"], deadline: "Rolling", acceptance: 55, scholarship: "UC International Scholarships", strengths: ["Engineering", "CS", "Sciences"], highlight: "Strong engineering on the South Island." },
    { id: "massey", name: "Massey University", country: "New Zealand", city: "Palmerston North", rank: 239, natRank: 5, type: "Public", founded: 1927, website: "massey.ac.nz", programs: ["Master of IT", "Master of Analytics", "MBA", "Master of Engineering", "Master of Aviation"], ielts: 6.5, gre: "Optional", gmat: 550, gpa: "3.0/4.0 (B)", tuitionUSD: 24e3, feeNote: "NZD 38k/yr", intakes: ["Feb", "Jul"], deadline: "Rolling", acceptance: 58, scholarship: "Massey International Excellence", strengths: ["Agriculture", "Aviation", "IT"], highlight: "Leading for agri-science & aviation." },
    // Singapore
    { id: "ntu", name: "Nanyang Technological University (NTU)", country: "Singapore", city: "Singapore", rank: 15, natRank: 2, type: "Public", founded: 1991, website: "ntu.edu.sg", programs: ["MSc Computer Science", "MSc AI", "MSc Data Science", "MBA (Nanyang)", "MSc Financial Eng"], ielts: 6.5, gre: "Recommended", gmat: 670, gpa: "3.3/4.0", tuitionUSD: 3e4, feeNote: "SGD 40\u201355k/yr", intakes: ["Aug (Fall)", "Jan"], deadline: "Nov\u2013Mar", acceptance: 20, scholarship: "NTU Research Scholarships", strengths: ["Engineering", "AI", "Business"], highlight: "World top-20; engineering & AI powerhouse." },
    { id: "smu", name: "Singapore Management University (SMU)", country: "Singapore", city: "Singapore", rank: 545, natRank: 3, type: "Public", founded: 2e3, website: "smu.edu.sg", programs: ["MSc Computing & Innovation", "MSc Data Science", "MBA", "MSc Finance", "MSc Business Analytics"], ielts: 6.5, gre: "Recommended", gmat: 650, gpa: "3.3/4.0", tuitionUSD: 32e3, feeNote: "SGD 45\u201360k/yr", intakes: ["Aug (Fall)", "Jan"], deadline: "Rolling", acceptance: 25, scholarship: "SMU Scholarships", strengths: ["Business", "Analytics", "Finance"], highlight: "Business & analytics specialist in the CBD." },
    { id: "sutd", name: "Singapore University of Technology & Design", country: "Singapore", city: "Singapore", rank: 440, natRank: 4, type: "Public", founded: 2009, website: "sutd.edu.sg", programs: ["Master of Computer Science", "MSc Data Science", "Master of Architecture", "MSc Tech & Design", "MSc Security"], ielts: 6.5, gre: "Recommended", gmat: null, gpa: "3.3/4.0", tuitionUSD: 28e3, feeNote: "SGD 38\u201350k/yr", intakes: ["Sep", "Jan"], deadline: "Rolling", acceptance: 30, scholarship: "SUTD Graduate Scholarships", strengths: ["Design", "CS", "Architecture"], highlight: "MIT-collaboration design-and-tech university." },
    // Netherlands
    { id: "uva", name: "University of Amsterdam", country: "Netherlands", city: "Amsterdam", rank: 53, natRank: 2, type: "Public", founded: 1632, website: "uva.nl", programs: ["MSc Artificial Intelligence", "MSc Data Science", "MSc Computer Science", "MSc Economics", "MSc Finance"], ielts: 6.5, gre: "Optional", gmat: 600, gpa: "3.0/4.0", tuitionUSD: 18e3, feeNote: "\u20AC15\u201318k/yr", intakes: ["Sep"], deadline: "Apr 1 (non-EU)", acceptance: 35, scholarship: "Amsterdam Merit, Holland Scholarship", strengths: ["AI", "Economics", "Humanities"], highlight: "Top European university for AI & economics." },
    { id: "eindhoven", name: "Eindhoven University of Technology", country: "Netherlands", city: "Eindhoven", rank: 124, natRank: 4, type: "Public", founded: 1956, website: "tue.nl", programs: ["MSc Computer Science & Eng", "MSc Data Science", "MSc Embedded Systems", "MSc Mechanical Eng", "MSc AI"], ielts: 6.5, gre: "Optional", gmat: null, gpa: "3.0/4.0", tuitionUSD: 22e3, feeNote: "\u20AC18\u201320k/yr", intakes: ["Sep", "Feb"], deadline: "Apr 1 / Nov 1", acceptance: 40, scholarship: "ALSP, Holland Scholarship", strengths: ["Electrical Eng", "CS", "Embedded Systems"], highlight: "Top European tech university in 'Brainport'." },
    { id: "utrecht", name: "Utrecht University", country: "Netherlands", city: "Utrecht", rank: 107, natRank: 3, type: "Public", founded: 1636, website: "uu.nl", programs: ["MSc Computing Science", "MSc Data Science", "MSc AI", "MSc Business Informatics", "MSc Economics"], ielts: 6.5, gre: "Optional", gmat: null, gpa: "3.0/4.0", tuitionUSD: 2e4, feeNote: "\u20AC17\u201319k/yr", intakes: ["Sep"], deadline: "Apr 1 (non-EU)", acceptance: 40, scholarship: "Utrecht Excellence Scholarship", strengths: ["AI", "Life Sciences", "Computing"], highlight: "One of Europe's oldest, top-ranked." },
    { id: "groningen", name: "University of Groningen", country: "Netherlands", city: "Groningen", rank: 139, natRank: 5, type: "Public", founded: 1614, website: "rug.nl", programs: ["MSc Computing Science", "MSc Data Science", "MSc AI", "MSc Economics", "MSc Finance"], ielts: 6.5, gre: "Optional", gmat: 600, gpa: "3.0/4.0", tuitionUSD: 18e3, feeNote: "\u20AC15\u201318k/yr", intakes: ["Sep"], deadline: "May 1 (non-EU)", acceptance: 45, scholarship: "Eric Bleumink Fund, Holland Scholarship", strengths: ["AI", "Economics", "Energy"], highlight: "Historic university; strong AI & energy." },
    { id: "erasmus", name: "Erasmus University Rotterdam", country: "Netherlands", city: "Rotterdam", rank: 176, natRank: 6, type: "Public", founded: 1913, website: "eur.nl", programs: ["MSc Business Analytics", "MSc Finance", "MBA (RSM)", "MSc Economics", "MSc Data Science"], ielts: 6.5, gre: "Recommended", gmat: 600, gpa: "3.0/4.0", tuitionUSD: 2e4, feeNote: "\u20AC16\u201319k/yr", intakes: ["Sep"], deadline: "Apr\u2013May", acceptance: 40, scholarship: "Erasmus Trustfund, Holland Scholarship", strengths: ["Business (RSM)", "Economics", "Finance"], highlight: "Top European business & economics school." }
  ];
  const COUNTRY_INFO = {
    USA: {
      psw: "OPT: 12 months (36 months for STEM degrees)",
      living: "$12,000\u201320,000/yr",
      visa: "F-1 student visa",
      work: "20 hrs/week on-campus during term; full-time in breaks",
      dependents: "F-2 dependents allowed (cannot work)",
      checklist: ["Academic transcripts", "Statement of Purpose", "2\u20133 Letters of Recommendation", "Resume / CV", "GRE/GMAT (if required)", "IELTS / TOEFL", "Application fee", "Passport copy", "Financial proof (I-20)"],
      deadlines: "Fall: Dec\u2013Jan \xB7 Spring: Sep\u2013Oct"
    },
    UK: {
      psw: "Graduate Route: 2 years (3 for PhD)",
      living: "\xA312,000\u201315,000/yr (\xA313,347 for visa)",
      visa: "Student visa (Tier 4)",
      work: "20 hrs/week during term",
      dependents: "Dependents only for PhD/long courses",
      checklist: ["Academic transcripts", "Personal Statement", "1\u20132 References", "CV", "IELTS UKVI", "Passport", "Financial proof (CAS)", "Degree certificate"],
      deadlines: "Rolling; apply by Jan for Sep intake"
    },
    Canada: {
      psw: "PGWP: up to 3 years",
      living: "CAD 12,000\u201318,000/yr (CAD 20,635 for visa)",
      visa: "Study permit",
      work: "24 hrs/week off-campus during term",
      dependents: "Spouse open work permit available",
      checklist: ["Transcripts", "Statement of Purpose", "2\u20133 LORs", "Resume", "IELTS / TOEFL", "GRE (if required)", "Passport", "Proof of funds (GIC)", "Application fee"],
      deadlines: "Fall: Dec\u2013Feb \xB7 Winter: Aug\u2013Sep"
    },
    Australia: {
      psw: "Temporary Graduate visa (485): 2\u20134 years",
      living: "AUD 21,000/yr (visa requirement)",
      visa: "Student visa (Subclass 500)",
      work: "48 hrs/fortnight during term",
      dependents: "Dependents can join; limited work",
      checklist: ["Transcripts", "Statement of Purpose", "CV", "IELTS / TOEFL / PTE", "Passport", "Financial proof", "GTE statement", "CoE"],
      deadlines: "Feb intake: Oct\u2013Dec \xB7 Jul intake: Apr\u2013May"
    },
    Germany: {
      psw: "18-month job-seeker visa after graduation",
      living: "\u20AC11,904/yr (blocked account)",
      visa: "German student visa",
      work: "120 full / 240 half days per year",
      dependents: "Family reunion possible",
      checklist: ["Transcripts (APS for India)", "SOP / Motivation letter", "LORs", "CV", "IELTS / TOEFL", "GRE (if required)", "Blocked account proof", "APS certificate", "Passport"],
      deadlines: "Winter: by May 31 \xB7 Summer: by Nov 30"
    },
    Ireland: {
      psw: "Stay Back: up to 2 years (master's)",
      living: "\u20AC10,000\u201312,000/yr",
      visa: "Irish study visa (Stamp 2)",
      work: "20 hrs/week during term",
      dependents: "Limited",
      checklist: ["Transcripts", "Statement of Purpose", "2 References", "CV", "IELTS", "Passport", "Proof of funds (\u20AC10,000)", "Application fee"],
      deadlines: "Rolling; apply by June for Sep"
    },
    "New Zealand": {
      psw: "Post-study work visa: up to 3 years",
      living: "NZD 20,000/yr (visa requirement)",
      visa: "Fee-paying student visa",
      work: "20 hrs/week during term",
      dependents: "Partner work visa available",
      checklist: ["Transcripts", "Statement of Purpose", "CV", "IELTS", "Passport", "Proof of funds", "Offer of place"],
      deadlines: "Mar intake: by Nov \xB7 Jul intake: by Apr"
    },
    Singapore: {
      psw: "1-year Long-Term Visit Pass to find work",
      living: "SGD 12,000\u201318,000/yr",
      visa: "Student's Pass",
      work: "16 hrs/week during term",
      dependents: "Limited",
      checklist: ["Transcripts", "Statement of Purpose", "2 LORs", "Resume", "IELTS / TOEFL", "GRE/GMAT (if required)", "Passport", "Financial proof"],
      deadlines: "Fall (Aug): Nov\u2013Mar"
    },
    Netherlands: {
      psw: "Orientation Year (zoekjaar): 1 year",
      living: "\u20AC10,800\u201313,200/yr",
      visa: "Residence permit (MVV)",
      work: "16 hrs/week during term",
      dependents: "Partner can work freely",
      checklist: ["Transcripts", "Motivation letter", "LORs", "CV", "IELTS / TOEFL", "GRE (recommended)", "Passport", "Proof of funds"],
      deadlines: "Sep intake: by Apr 1 (non-EU)"
    }
  };
  const PROCESS = {
    USA: ["Shortlist programs & note GRE/GMAT policy", "Take IELTS/TOEFL + GRE/GMAT if required", "Prepare SOP, 2\u20133 LORs, CV & transcripts", "Apply online (Fall deadlines Dec\u2013Jan)", "Pay application fee; submit", "Receive decision \u2192 I-20 \u2192 F-1 visa"],
    UK: ["Pick one-year master's programs", "Meet IELTS (6.5\u20137.5) & 2:1/First equivalent", "Write personal statement + 1\u20132 references", "Apply directly on university portal (rolling)", "Receive offer (conditional/unconditional)", "Pay deposit \u2192 CAS \u2192 Student visa"],
    Canada: ["Shortlist programs & check GRE policy", "IELTS 6.5\u20137.0; prepare SOP, LORs, transcripts", "Apply online (Fall deadlines Dec\u2013Feb)", "Receive offer letter", "Pay tuition deposit \u2192 get acceptance", "Apply for study permit (GIC)"],
    Australia: ["Choose Feb or Jul intake", "Meet IELTS 6.5; prepare SOP, CV, transcripts", "Apply via portal or agent (rolling)", "Receive offer \u2192 accept & pay deposit", "Get CoE (Confirmation of Enrolment)", "Apply for Subclass 500 student visa"],
    Germany: ["Find English-taught master's (DAAD/uni-assist)", "Meet IELTS 6.5 + GRE if required; get APS", "Apply via uni-assist or university portal", "Receive admission letter", "Open blocked account (\u2248\u20AC11,904)", "Apply for German student visa"],
    Ireland: ["Shortlist programs", "Meet IELTS 6.5; SOP + references", "Apply online (rolling, Sep intake)", "Receive offer \u2192 pay deposit", "Get letter for visa", "Apply for Irish study visa"],
    "New Zealand": ["Choose Mar or Jul intake", "Meet IELTS 6.5; SOP, CV, transcripts", "Apply online", "Receive offer of place \u2192 pay tuition", "Get receipt for visa", "Apply for student visa"],
    Singapore: ["Shortlist programs & check GRE/GMAT policy", "Meet IELTS 6.5; SOP, LORs, resume", "Apply online (Aug intake)", "Receive offer \u2192 accept", "Pay deposit", "Apply for Student's Pass"],
    Netherlands: ["Find English-taught master's (Studielink)", "Meet IELTS 6.5 + GRE if recommended", "Apply by Apr 1 (non-EU)", "Receive offer \u2192 pay deposit", "Arrange proof of funds", "Apply for MVV residence permit"]
  };
  const CONC = {
    toefl: { 6: 72, 6.5: 85, 7: 94, 7.5: 105, 8: 115 },
    pte: { 6: 55, 6.5: 58, 7: 65, 7.5: 72, 8: 80 },
    duolingo: { 6: 105, 6.5: 110, 7: 120, 7.5: 130, 8: 140 }
  };
  const conc = (field, ielts) => CONC[field][ielts] || CONC[field][Math.round(ielts)] || CONC[field][6.5];
  C.forEach((c) => {
    if (c.toefl == null) c.toefl = conc("toefl", c.ielts);
    if (c.pte == null) c.pte = conc("pte", c.ielts);
    if (c.duolingo == null) c.duolingo = conc("duolingo", c.ielts);
    if (c.intlPct == null) c.intlPct = 30;
    if (c.appFee == null) c.appFee = "$50\u2013100";
    if (c.workEx == null) c.workEx = /MBA/i.test(c.programs.join(" ")) ? "2\u20134 yrs (MBA only)" : null;
    if (c.classProfile == null) c.classProfile = c.acceptance < 15 ? "Highly selective intake" : c.acceptance < 40 ? "Selective intake" : "Moderately selective";
    if (c.alumni == null) c.alumni = null;
  });
  window.LP_COLLEGES = C;
  window.LP_COLLEGE_PROCESS = PROCESS;
  window.LP_COLLEGE_COUNTRY_INFO = COUNTRY_INFO;
  window.LP_COLLEGE_COUNTRIES = [...new Set(C.map((c) => c.country))];
  window.LP_COLLEGE_PROGRAMS = [...new Set(C.flatMap((c) => c.programs))].sort();
})();
