/* global window */
"use strict";
// LandingPrep — Language Learning Hub data (German = flagship, French secondary).
// Data-driven so courses/levels expand without touching the UI. Pronunciation uses
// the live natural voice (window.LP_TTS.speakOne). Schema:
//   { id, name, native, flag, blurb, why[], exams[{name,desc}], levels[],
//     course:[{id,level,title,grammar, vocab:[{w,en,ex}]}],
//     quiz:[{q,options[],answer}] }
(function () {
  const GERMAN = {
    id: "german", name: "German", native: "Deutsch", flag: "🇩🇪",
    blurb: "Study tuition-free in Germany, Austria & Switzerland. German is the #1 language for affordable, high-quality study abroad.",
    why: [
      "Germany has world-class universities with little or no tuition — but most programmes and daily life need German.",
      "A1–B1 German unlocks the Germany student visa, blocked-account jobs, and far better part-time work.",
      "Austria, Switzerland and Liechtenstein also study in German.",
      "Speaking German makes settling, working and getting PR dramatically easier.",
    ],
    exams: [
      { name: "Goethe-Zertifikat (A1–C2)", desc: "The most recognised German exam worldwide — accepted for study, work and visas." },
      { name: "TestDaF", desc: "Academic German for university admission (level B2/C1). Required by many Master's programmes." },
      { name: "telc Deutsch", desc: "Widely accepted in Germany for jobs, residence and integration courses." },
      { name: "TestAS", desc: "Aptitude test for international students applying to German universities." },
      { name: "DSH", desc: "University-run German exam (DSH-1/2/3) for admission to German-taught degrees." },
    ],
    levels: ["A1", "A2", "B1", "B2", "C1", "C2"],
    course: [
      {
        id: "de-a1-u1", level: "A1", title: "Greetings & Introductions",
        grammar: "German has formal (Sie) and informal (du) 'you'. Use Sie with strangers and in formal settings, du with friends and family.",
        vocab: [
          { w: "Hallo", en: "Hello", ex: "Hallo! Wie geht es dir?" },
          { w: "Guten Morgen", en: "Good morning", ex: "Guten Morgen, Frau Müller." },
          { w: "Guten Tag", en: "Good day / Hello", ex: "Guten Tag, ich heiße Anna." },
          { w: "Guten Abend", en: "Good evening", ex: "Guten Abend zusammen!" },
          { w: "Gute Nacht", en: "Good night", ex: "Gute Nacht, schlaf gut!" },
          { w: "Tschüss", en: "Bye", ex: "Tschüss, bis morgen!" },
          { w: "Auf Wiedersehen", en: "Goodbye (formal)", ex: "Auf Wiedersehen, Herr Klein." },
          { w: "Ich heiße …", en: "My name is …", ex: "Ich heiße Sofia." },
          { w: "Wie heißt du?", en: "What's your name? (informal)", ex: "Hallo, wie heißt du?" },
          { w: "Wie geht es dir?", en: "How are you?", ex: "Wie geht es dir heute?" },
          { w: "Mir geht es gut", en: "I'm fine", ex: "Danke, mir geht es gut." },
          { w: "Danke", en: "Thank you", ex: "Danke schön!" },
          { w: "Bitte", en: "Please / You're welcome", ex: "Bitte, gern geschehen." },
          { w: "Ja / Nein", en: "Yes / No", ex: "Ja, gern. Nein, danke." },
        ],
      },
      {
        id: "de-a1-u2", level: "A1", title: "Numbers, Days & Time",
        grammar: "German numbers above 20 are 'reversed': 21 = einundzwanzig (one-and-twenty). 'Uhr' = o'clock; 'halb drei' = 2:30 (half to three).",
        vocab: [
          { w: "eins, zwei, drei", en: "one, two, three", ex: "Ich habe drei Bücher." },
          { w: "vier, fünf, sechs", en: "four, five, six", ex: "Es ist sechs Uhr." },
          { w: "sieben, acht, neun, zehn", en: "seven … ten", ex: "Zehn Euro, bitte." },
          { w: "elf, zwölf", en: "eleven, twelve", ex: "Es ist zwölf Uhr." },
          { w: "zwanzig", en: "twenty", ex: "Ich bin zwanzig Jahre alt." },
          { w: "einundzwanzig", en: "twenty-one", ex: "Er ist einundzwanzig." },
          { w: "hundert", en: "hundred", ex: "Das kostet hundert Euro." },
          { w: "Montag, Dienstag", en: "Monday, Tuesday", ex: "Am Montag habe ich Deutsch." },
          { w: "Samstag, Sonntag", en: "Saturday, Sunday", ex: "Am Sonntag schlafe ich lange." },
          { w: "Wochenende", en: "weekend", ex: "Schönes Wochenende!" },
          { w: "heute / morgen / gestern", en: "today / tomorrow / yesterday", ex: "Heute ist Dienstag." },
          { w: "Wie spät ist es?", en: "What time is it?", ex: "Entschuldigung, wie spät ist es?" },
          { w: "Es ist halb drei", en: "It's half past two (2:30)", ex: "Es ist halb drei." },
          { w: "Viertel nach / vor", en: "quarter past / to", ex: "Viertel nach acht." },
        ],
      },
      {
        id: "de-a1-u3", level: "A1", title: "Articles & Gender (der/die/das)",
        grammar: "Every German noun has a gender: der (m), die (f), das (n). Always learn the article WITH the noun. The plural article is always 'die'.",
        vocab: [
          { w: "der Mann", en: "the man", ex: "Der Mann ist nett." },
          { w: "die Frau", en: "the woman", ex: "Die Frau heißt Maria." },
          { w: "das Kind", en: "the child", ex: "Das Kind spielt." },
          { w: "der Tisch", en: "the table", ex: "Der Tisch ist groß." },
          { w: "die Lampe", en: "the lamp", ex: "Die Lampe ist neu." },
          { w: "das Buch", en: "the book", ex: "Das Buch ist interessant." },
          { w: "der Stuhl", en: "the chair", ex: "Der Stuhl ist bequem." },
          { w: "die Tür", en: "the door", ex: "Die Tür ist offen." },
          { w: "das Fenster", en: "the window", ex: "Das Fenster ist groß." },
          { w: "ein / eine", en: "a / an (m,n / f)", ex: "Ich habe eine Frage." },
          { w: "kein / keine", en: "no / not a", ex: "Ich habe keine Zeit." },
          { w: "die Bücher", en: "the books (plural)", ex: "Die Bücher sind teuer." },
        ],
      },
      {
        id: "de-a1-u4", level: "A1", title: "Present Tense & Common Verbs",
        grammar: "Regular verbs: stem + endings -e, -st, -t, -en, -t, -en. 'sein' (to be): ich bin, du bist, er ist, wir sind. 'haben' (to have): ich habe, du hast, er hat.",
        vocab: [
          { w: "sein (ich bin)", en: "to be (I am)", ex: "Ich bin Student." },
          { w: "haben (ich habe)", en: "to have (I have)", ex: "Ich habe Zeit." },
          { w: "kommen", en: "to come", ex: "Ich komme aus Indien." },
          { w: "wohnen", en: "to live", ex: "Ich wohne in Berlin." },
          { w: "sprechen", en: "to speak", ex: "Sprichst du Deutsch?" },
          { w: "lernen", en: "to learn", ex: "Ich lerne Deutsch." },
          { w: "arbeiten", en: "to work", ex: "Er arbeitet in München." },
          { w: "verstehen", en: "to understand", ex: "Ich verstehe das nicht." },
          { w: "gehen", en: "to go", ex: "Ich gehe zur Uni." },
          { w: "machen", en: "to do / make", ex: "Was machst du?" },
          { w: "essen / trinken", en: "to eat / drink", ex: "Ich esse einen Apfel." },
          { w: "heißen", en: "to be called", ex: "Wie heißt du?" },
        ],
      },
      {
        id: "de-a1-u5", level: "A1", title: "Family & People",
        grammar: "Possessives: mein (my), dein (your), sein/ihr (his/her). They take -e before feminine/plural nouns: meine Mutter, mein Vater.",
        vocab: [
          { w: "die Familie", en: "the family", ex: "Meine Familie ist groß." },
          { w: "die Mutter", en: "the mother", ex: "Meine Mutter heißt Petra." },
          { w: "der Vater", en: "the father", ex: "Mein Vater arbeitet viel." },
          { w: "die Eltern", en: "the parents", ex: "Meine Eltern wohnen in Indien." },
          { w: "der Bruder", en: "the brother", ex: "Mein Bruder ist 18." },
          { w: "die Schwester", en: "the sister", ex: "Meine Schwester studiert." },
          { w: "der Freund / die Freundin", en: "friend (m / f)", ex: "Mein Freund heißt Tom." },
          { w: "der Mann / die Frau", en: "husband / wife", ex: "Das ist meine Frau." },
          { w: "das Kind / die Kinder", en: "child / children", ex: "Sie haben zwei Kinder." },
          { w: "jung / alt", en: "young / old", ex: "Mein Bruder ist jung." },
          { w: "verheiratet / ledig", en: "married / single", ex: "Ich bin ledig." },
        ],
      },
      {
        id: "de-a1-u6", level: "A1", title: "Food, Drink & the Café",
        grammar: "Order politely with 'Ich möchte …' or 'Ich nehme …' (I'll take …). 'einen' (m), 'eine' (f), 'ein' (n) are accusative articles after these verbs.",
        vocab: [
          { w: "das Wasser", en: "water", ex: "Ein Wasser, bitte." },
          { w: "der Kaffee", en: "coffee", ex: "Ich möchte einen Kaffee." },
          { w: "der Tee", en: "tea", ex: "Ich trinke gern Tee." },
          { w: "das Brot", en: "bread", ex: "Das Brot ist frisch." },
          { w: "der Apfel", en: "apple", ex: "Ich esse einen Apfel." },
          { w: "das Ei / die Eier", en: "egg / eggs", ex: "Ich möchte zwei Eier." },
          { w: "der Käse", en: "cheese", ex: "Der Käse ist lecker." },
          { w: "die Milch", en: "milk", ex: "Mit Milch, bitte." },
          { w: "das Bier", en: "beer", ex: "Ein Bier, bitte." },
          { w: "Ich möchte …", en: "I would like …", ex: "Ich möchte ein Brot, bitte." },
          { w: "die Rechnung, bitte", en: "the bill, please", ex: "Die Rechnung, bitte!" },
          { w: "lecker", en: "tasty", ex: "Das schmeckt lecker." },
        ],
      },
      {
        id: "de-a1-u7", level: "A1", title: "Shopping & Prices",
        grammar: "Ask prices with 'Was kostet …?' (singular) / 'Was kosten …?' (plural). Euro amounts: 'drei Euro fünfzig' = €3.50.",
        vocab: [
          { w: "Was kostet das?", en: "How much is that?", ex: "Was kostet das Ticket?" },
          { w: "der Euro / der Cent", en: "euro / cent", ex: "Das kostet fünf Euro." },
          { w: "billig / teuer", en: "cheap / expensive", ex: "Das ist zu teuer." },
          { w: "das Geld", en: "money", ex: "Ich habe kein Geld dabei." },
          { w: "der Supermarkt", en: "supermarket", ex: "Ich gehe in den Supermarkt." },
          { w: "die Kasse", en: "the checkout", ex: "Die Kasse ist dort." },
          { w: "bar / mit Karte", en: "cash / by card", ex: "Mit Karte, bitte." },
          { w: "die Tüte", en: "the bag", ex: "Eine Tüte, bitte." },
          { w: "kaufen", en: "to buy", ex: "Ich kaufe Brot und Milch." },
          { w: "die Größe", en: "the size", ex: "Welche Größe haben Sie?" },
          { w: "zusammen / getrennt", en: "together / separately", ex: "Zusammen oder getrennt?" },
        ],
      },
      {
        id: "de-a1-u8", level: "A1", title: "Daily Routine & Hobbies",
        grammar: "Frequency words go after the verb: 'Ich spiele oft Fußball.' Use 'gern' to say you like doing something: 'Ich lese gern.'",
        vocab: [
          { w: "aufstehen", en: "to get up", ex: "Ich stehe um sieben Uhr auf." },
          { w: "frühstücken", en: "to have breakfast", ex: "Ich frühstücke um acht." },
          { w: "schlafen", en: "to sleep", ex: "Ich schlafe acht Stunden." },
          { w: "spielen", en: "to play", ex: "Ich spiele gern Tennis." },
          { w: "lesen", en: "to read", ex: "Am Abend lese ich ein Buch." },
          { w: "hören", en: "to listen", ex: "Ich höre gern Musik." },
          { w: "der Sport / der Fußball", en: "sport / football", ex: "Fußball ist mein Hobby." },
          { w: "die Musik / der Film", en: "music / film", ex: "Ich sehe gern Filme." },
          { w: "oft / manchmal / nie", en: "often / sometimes / never", ex: "Ich koche manchmal." },
          { w: "gern", en: "(to like doing)", ex: "Ich schwimme gern." },
          { w: "das Hobby", en: "the hobby", ex: "Was ist dein Hobby?" },
        ],
      },
      {
        id: "de-a1-u9", level: "A1", title: "City, Directions & Transport",
        grammar: "Ask the way with 'Wo ist …?' (Where is …?). Answer with 'links' (left), 'rechts' (right), 'geradeaus' (straight ahead).",
        vocab: [
          { w: "Wo ist …?", en: "Where is …?", ex: "Wo ist der Bahnhof?" },
          { w: "der Bahnhof", en: "the train station", ex: "Der Bahnhof ist dort." },
          { w: "die Haltestelle", en: "the (bus) stop", ex: "Die Haltestelle ist hier." },
          { w: "der Bus / die U-Bahn", en: "bus / underground", ex: "Ich fahre mit dem Bus." },
          { w: "der Zug", en: "the train", ex: "Der Zug kommt um neun." },
          { w: "links / rechts", en: "left / right", ex: "Gehen Sie nach links." },
          { w: "geradeaus", en: "straight ahead", ex: "Gehen Sie geradeaus." },
          { w: "die Straße", en: "the street", ex: "Die Straße ist lang." },
          { w: "die Apotheke", en: "the pharmacy", ex: "Wo ist die Apotheke?" },
          { w: "das Krankenhaus", en: "the hospital", ex: "Das Krankenhaus ist groß." },
          { w: "die Karte / das Ticket", en: "map / ticket", ex: "Ein Ticket, bitte." },
        ],
      },
      {
        id: "de-a1-u10", level: "A1", title: "Survival German (uni, bank, doctor)",
        grammar: "Polite requests: 'Könnten Sie …?' (Could you …?) and 'Ich brauche …' (I need …). Say you don't understand: 'Ich verstehe nicht. Langsam, bitte.'",
        vocab: [
          { w: "Entschuldigung", en: "Excuse me / Sorry", ex: "Entschuldigung, wo ist die Uni?" },
          { w: "Ich verstehe nicht", en: "I don't understand", ex: "Langsam, bitte. Ich verstehe nicht." },
          { w: "Sprechen Sie Englisch?", en: "Do you speak English?", ex: "Sprechen Sie Englisch?" },
          { w: "Können Sie das wiederholen?", en: "Can you repeat that?", ex: "Können Sie das bitte wiederholen?" },
          { w: "die Universität", en: "the university", ex: "Die Universität ist groß." },
          { w: "die Wohnung", en: "the apartment", ex: "Ich suche eine Wohnung." },
          { w: "das Konto", en: "the (bank) account", ex: "Ich brauche ein Konto." },
          { w: "der Termin", en: "the appointment", ex: "Ich habe einen Termin." },
          { w: "der Arzt / die Ärztin", en: "doctor (m / f)", ex: "Ich gehe zum Arzt." },
          { w: "der Ausweis / der Pass", en: "ID / passport", ex: "Hier ist mein Pass." },
          { w: "Hilfe!", en: "Help!", ex: "Können Sie mir helfen?" },
        ],
      },
    ],
    quiz: [
      { q: "How do you say 'Good morning' in German?", options: ["Guten Abend", "Guten Morgen", "Gute Nacht", "Guten Tag"], answer: 1 },
      { q: "'Ich heiße Anna' means …", options: ["I live in Anna", "I like Anna", "My name is Anna", "I am from Anna"], answer: 2 },
      { q: "Which is the correct article for 'Frau' (woman)?", options: ["der", "die", "das", "den"], answer: 1 },
      { q: "'Danke' means …", options: ["Please", "Sorry", "Thank you", "Hello"], answer: 2 },
      { q: "How do you ask 'What's your name?' (informal)?", options: ["Wie geht's?", "Wie heißt du?", "Wer bist du?", "Wo wohnst du?"], answer: 1 },
      { q: "The number 'zwanzig' is …", options: ["12", "20", "2", "200"], answer: 1 },
      { q: "'Ich komme aus Indien' means …", options: ["I live in India", "I come from India", "I go to India", "I like India"], answer: 1 },
      { q: "Formal 'you' in German is …", options: ["du", "ihr", "Sie", "es"], answer: 2 },
      { q: "'Was kostet das?' means …", options: ["What is that?", "Where is that?", "How much is that?", "Who is that?"], answer: 2 },
      { q: "The verb 'lernen' means …", options: ["to live", "to learn", "to work", "to come"], answer: 1 },
      { q: "'Meine Mutter' means …", options: ["my father", "my sister", "my mother", "my friend"], answer: 2 },
      { q: "Which means 'turn left'?", options: ["nach rechts", "geradeaus", "nach links", "zurück"], answer: 2 },
      { q: "'Ich möchte einen Kaffee' means …", options: ["I have a coffee", "I would like a coffee", "I make a coffee", "I see a coffee"], answer: 1 },
      { q: "The plural of 'das Buch' is …", options: ["die Buchs", "die Bücher", "die Buche", "der Bücher"], answer: 1 },
    ],
  };

  const FRENCH = {
    id: "french", name: "French", native: "Français", flag: "🇫🇷",
    blurb: "Study in France, Belgium, parts of Canada (Québec) and Switzerland. French opens affordable EU study and a huge job market.",
    why: [
      "France has low-tuition public universities and the Campus France pathway — French helps admission and daily life.",
      "Québec (Canada) actively recruits French-speaking students with fast PR routes.",
      "DELF/DALF and TCF are accepted for study and immigration across the Francophone world.",
    ],
    exams: [
      { name: "DELF (A1–B2)", desc: "Diplôme d'études en langue française — lifelong, recognised for study & immigration." },
      { name: "DALF (C1–C2)", desc: "Advanced French diploma for university and professional use." },
      { name: "TCF", desc: "Test de connaissance du français — used for Campus France, Québec immigration and citizenship." },
      { name: "TEF", desc: "Accepted for Canadian immigration (Express Entry) and French nationality." },
    ],
    levels: ["A1", "A2", "B1", "B2", "C1", "C2"],
    course: [
      {
        id: "fr-a1-u1", level: "A1", title: "Greetings & Introductions",
        grammar: "French has formal (vous) and informal (tu) 'you'. Use vous with strangers, tu with friends. 'Je m'appelle …' = my name is …",
        vocab: [
          { w: "Bonjour", en: "Hello / Good day", ex: "Bonjour, comment allez-vous ?" },
          { w: "Salut", en: "Hi (informal)", ex: "Salut ! Ça va ?" },
          { w: "Bonsoir", en: "Good evening", ex: "Bonsoir, madame." },
          { w: "Au revoir", en: "Goodbye", ex: "Au revoir, à demain !" },
          { w: "À bientôt", en: "See you soon", ex: "À bientôt !" },
          { w: "Je m'appelle …", en: "My name is …", ex: "Je m'appelle Léa." },
          { w: "Comment tu t'appelles ?", en: "What's your name? (informal)", ex: "Comment tu t'appelles ?" },
          { w: "Comment ça va ?", en: "How are you?", ex: "Salut, comment ça va ?" },
          { w: "Ça va bien", en: "I'm fine", ex: "Ça va bien, merci." },
          { w: "Enchanté(e)", en: "Nice to meet you", ex: "Enchanté de vous rencontrer." },
          { w: "Merci", en: "Thank you", ex: "Merci beaucoup !" },
          { w: "S'il vous plaît", en: "Please (formal)", ex: "Un café, s'il vous plaît." },
          { w: "Oui / Non", en: "Yes / No", ex: "Oui, merci. Non, merci." },
        ],
      },
      {
        id: "fr-a1-u2", level: "A1", title: "Numbers, Days & Time",
        grammar: "French nouns are masculine (le) or feminine (la). Learn the article with the noun. Plural = les. Time: 'Il est trois heures' = it's 3 o'clock.",
        vocab: [
          { w: "un, deux, trois", en: "one, two, three", ex: "J'ai trois livres." },
          { w: "quatre, cinq, six", en: "four, five, six", ex: "Il est six heures." },
          { w: "sept, huit, neuf, dix", en: "seven … ten", ex: "Dix euros, s'il vous plaît." },
          { w: "vingt", en: "twenty", ex: "J'ai vingt ans." },
          { w: "cent", en: "hundred", ex: "Ça coûte cent euros." },
          { w: "lundi, mardi", en: "Monday, Tuesday", ex: "Lundi, j'ai un cours." },
          { w: "le week-end", en: "the weekend", ex: "Bon week-end !" },
          { w: "aujourd'hui / demain", en: "today / tomorrow", ex: "Aujourd'hui, c'est lundi." },
          { w: "Quelle heure est-il ?", en: "What time is it?", ex: "Excusez-moi, quelle heure est-il ?" },
          { w: "Il est midi", en: "It's noon", ex: "Il est midi pile." },
          { w: "et demie / et quart", en: "half past / quarter past", ex: "Il est huit heures et demie." },
        ],
      },
      {
        id: "fr-a1-u3", level: "A1", title: "Articles, Gender & Common Verbs",
        grammar: "le (m) / la (f) / les (plural). Key verbs: être (je suis, tu es, il est) and avoir (j'ai, tu as, il a). Regular -er: je parle, tu parles, nous parlons.",
        vocab: [
          { w: "le / la / les", en: "the (m / f / plural)", ex: "La fille et le garçon." },
          { w: "un / une", en: "a / an (m / f)", ex: "J'ai une question." },
          { w: "être (je suis)", en: "to be (I am)", ex: "Je suis étudiant." },
          { w: "avoir (j'ai)", en: "to have (I have)", ex: "J'ai un livre." },
          { w: "parler", en: "to speak", ex: "Je parle français." },
          { w: "habiter", en: "to live", ex: "J'habite à Lyon." },
          { w: "venir", en: "to come", ex: "Je viens d'Inde." },
          { w: "aller", en: "to go", ex: "Je vais à l'université." },
          { w: "faire", en: "to do / make", ex: "Qu'est-ce que tu fais ?" },
          { w: "comprendre", en: "to understand", ex: "Je ne comprends pas." },
          { w: "ne … pas", en: "not (negation)", ex: "Je ne parle pas allemand." },
        ],
      },
      {
        id: "fr-a1-u4", level: "A1", title: "Family & People",
        grammar: "Possessives: mon/ma/mes (my), ton/ta/tes (your). Use mon before masculine, ma before feminine: mon père, ma mère, mes parents.",
        vocab: [
          { w: "la famille", en: "the family", ex: "Ma famille est grande." },
          { w: "la mère / le père", en: "mother / father", ex: "Ma mère s'appelle Marie." },
          { w: "les parents", en: "parents", ex: "Mes parents habitent en Inde." },
          { w: "le frère / la sœur", en: "brother / sister", ex: "Mon frère a 18 ans." },
          { w: "l'ami / l'amie", en: "friend (m / f)", ex: "Mon ami s'appelle Paul." },
          { w: "le mari / la femme", en: "husband / wife", ex: "C'est ma femme." },
          { w: "l'enfant / les enfants", en: "child / children", ex: "Ils ont deux enfants." },
          { w: "jeune / vieux", en: "young / old", ex: "Mon frère est jeune." },
          { w: "marié(e) / célibataire", en: "married / single", ex: "Je suis célibataire." },
          { w: "le garçon / la fille", en: "boy / girl", ex: "La fille est gentille." },
        ],
      },
      {
        id: "fr-a1-u5", level: "A1", title: "Food, Drink & the Café",
        grammar: "Order with 'Je voudrais …' (I would like …) or 'Je prends …' (I'll have …). 'un' (m), 'une' (f), 'du/de la' (some).",
        vocab: [
          { w: "l'eau", en: "water", ex: "Une eau, s'il vous plaît." },
          { w: "le café", en: "coffee", ex: "Je voudrais un café." },
          { w: "le thé", en: "tea", ex: "J'aime le thé." },
          { w: "le pain", en: "bread", ex: "Le pain est frais." },
          { w: "la pomme", en: "apple", ex: "Je mange une pomme." },
          { w: "le fromage", en: "cheese", ex: "Le fromage est bon." },
          { w: "le lait", en: "milk", ex: "Avec du lait, s'il vous plaît." },
          { w: "le vin", en: "wine", ex: "Un verre de vin, s'il vous plaît." },
          { w: "Je voudrais …", en: "I would like …", ex: "Je voudrais un thé." },
          { w: "L'addition, s'il vous plaît", en: "The bill, please", ex: "L'addition, s'il vous plaît !" },
          { w: "délicieux", en: "delicious", ex: "C'est délicieux !" },
        ],
      },
      {
        id: "fr-a1-u6", level: "A1", title: "Shopping & Prices",
        grammar: "Ask prices with 'Combien ça coûte ?' or 'C'est combien ?'. Euro amounts: 'trois euros cinquante' = €3.50.",
        vocab: [
          { w: "Combien ça coûte ?", en: "How much is it?", ex: "Combien ça coûte ?" },
          { w: "l'euro / le centime", en: "euro / cent", ex: "Ça coûte cinq euros." },
          { w: "cher / pas cher", en: "expensive / cheap", ex: "C'est trop cher." },
          { w: "l'argent", en: "money", ex: "Je n'ai pas d'argent." },
          { w: "le supermarché", en: "supermarket", ex: "Je vais au supermarché." },
          { w: "la caisse", en: "the checkout", ex: "La caisse est là-bas." },
          { w: "en espèces / par carte", en: "cash / by card", ex: "Par carte, s'il vous plaît." },
          { w: "le sac", en: "the bag", ex: "Un sac, s'il vous plaît." },
          { w: "acheter", en: "to buy", ex: "J'achète du pain." },
          { w: "la taille", en: "the size", ex: "Quelle taille ?" },
        ],
      },
      {
        id: "fr-a1-u7", level: "A1", title: "Daily Routine & Hobbies",
        grammar: "Say what you like with 'J'aime …' + verb: 'J'aime lire.' Frequency: souvent (often), parfois (sometimes), jamais (never).",
        vocab: [
          { w: "se lever", en: "to get up", ex: "Je me lève à sept heures." },
          { w: "dormir", en: "to sleep", ex: "Je dors huit heures." },
          { w: "manger", en: "to eat", ex: "Je mange à midi." },
          { w: "jouer", en: "to play", ex: "Je joue au foot." },
          { w: "lire", en: "to read", ex: "J'aime lire le soir." },
          { w: "écouter", en: "to listen", ex: "J'écoute de la musique." },
          { w: "regarder", en: "to watch", ex: "Je regarde un film." },
          { w: "le sport / le foot", en: "sport / football", ex: "Le foot est mon hobby." },
          { w: "souvent / parfois / jamais", en: "often / sometimes / never", ex: "Je cuisine parfois." },
          { w: "J'aime …", en: "I like …", ex: "J'aime nager." },
        ],
      },
      {
        id: "fr-a1-u8", level: "A1", title: "City, Directions & Survival",
        grammar: "Ask the way with 'Où est …?'. Directions: à gauche (left), à droite (right), tout droit (straight ahead). 'Je ne comprends pas' = I don't understand.",
        vocab: [
          { w: "Où est …?", en: "Where is …?", ex: "Où est la gare ?" },
          { w: "la gare", en: "the train station", ex: "La gare est là-bas." },
          { w: "l'arrêt de bus", en: "the bus stop", ex: "L'arrêt de bus est ici." },
          { w: "le bus / le métro", en: "bus / underground", ex: "Je prends le métro." },
          { w: "à gauche / à droite", en: "left / right", ex: "Tournez à gauche." },
          { w: "tout droit", en: "straight ahead", ex: "Allez tout droit." },
          { w: "la rue", en: "the street", ex: "La rue est longue." },
          { w: "Excusez-moi", en: "Excuse me", ex: "Excusez-moi, où est la gare ?" },
          { w: "Je ne comprends pas", en: "I don't understand", ex: "Désolé, je ne comprends pas." },
          { w: "Parlez-vous anglais ?", en: "Do you speak English?", ex: "Parlez-vous anglais ?" },
          { w: "l'université / l'appartement", en: "university / apartment", ex: "Je cherche un appartement." },
        ],
      },
    ],
    quiz: [
      { q: "How do you say 'Hello / Good day' in French?", options: ["Bonsoir", "Au revoir", "Bonjour", "Merci"], answer: 2 },
      { q: "'Je m'appelle Léa' means …", options: ["I like Léa", "My name is Léa", "I live in Léa", "I call Léa"], answer: 1 },
      { q: "'Merci' means …", options: ["Please", "Sorry", "Thank you", "Hello"], answer: 2 },
      { q: "The feminine article 'the' is …", options: ["le", "la", "les", "un"], answer: 1 },
      { q: "'Combien ça coûte ?' means …", options: ["Where is it?", "How much is it?", "What is it?", "Who is it?"], answer: 1 },
      { q: "Formal 'you' in French is …", options: ["tu", "il", "vous", "on"], answer: 2 },
      { q: "'Je voudrais un café' means …", options: ["I have a coffee", "I would like a coffee", "I make a coffee", "I see a coffee"], answer: 1 },
      { q: "Which exam is used for Canadian immigration?", options: ["DELF only", "TEF / TCF", "Goethe", "IELTS"], answer: 1 },
      { q: "'Ma mère' means …", options: ["my father", "my sister", "my mother", "my friend"], answer: 2 },
      { q: "Which means 'turn right'?", options: ["à gauche", "tout droit", "à droite", "en arrière"], answer: 2 },
      { q: "The verb 'habiter' means …", options: ["to eat", "to live", "to buy", "to read"], answer: 1 },
      { q: "'Quelle heure est-il ?' asks about …", options: ["the price", "the time", "the name", "the place"], answer: 1 },
    ],
  };

  window.LP_LANGUAGES = { german: GERMAN, french: FRENCH };
  window.LP_LANGUAGE_ORDER = ["german", "french"];
})();
