/* global window */
"use strict";

// LandingPrep — curated scholarship dataset for the Scholarship Finder.
// Figures are INDICATIVE; always confirm on the official scholarship site.
// Schema: { id, name, country, level, type, amount, who, deadline, highlight }
(function () {
  const S = [
{"id":"france-bgf-scholarship","name":"BGF (Bourse du Gouvernement Français) Master's Scholarship","country":"France","level":"Master's","type":"Government","amount":"€600–1,000/month + tuition waiver","who":"International students from eligible countries enrolled in French public Master's programs","deadline":"Varies (Spring for next academic year)","highlight":"Covers living costs and tuition at public universities; competitive selection."},
{"id":"france-erasmus-mundus","name":"Erasmus Mundus Joint Master's Scholarships","country":"France","level":"Master's","type":"Erasmus","amount":"€1,400/month + full tuition","who":"Students pursuing joint Master's degrees offered by European consortiums (many based in France)","deadline":"December/January annually","highlight":"Study across 2–3 European countries; includes mobility and living allowance."},
{"id":"italy-italian-government","name":"Italian Government Scholarship for International Students","country":"Italy","level":"Master's","type":"Government","amount":"€900–1,200/month + tuition waiver","who":"International Master's students enrolled at public Italian universities; merit-based selection","deadline":"March/April annually","highlight":"Covers living costs and waives tuition; competitive pool."},
{"id":"italy-sapienza-partnership","name":"Sapienza University Partnership Scholarships (India Focus)","country":"Italy","level":"Master's","type":"University","amount":"€5,000–10,000/yr","who":"Indian students pursuing Master's in Engineering, Computer Science, or Management at Sapienza","deadline":"April annually","highlight":"Dedicated partnership with Indian universities; partial tuition coverage."},
{"id":"sweden-kth-excellence","name":"KTH Excellence Scholarships","country":"Sweden","level":"Master's","type":"University","amount":"Fully funded (tuition + SEK 12,000/month)","who":"High-achieving international students in engineering and tech Master's programs","deadline":"December/January annually","highlight":"Covers full tuition and living costs; limited availability; highly competitive."},
{"id":"sweden-lund-scholarship","name":"Lund University Global Scholarship Programme","country":"Sweden","level":"Master's","type":"University","amount":"SEK 80,000–140,000/yr (~€8,000–14,000)","who":"International Master's students at Lund; merit-based with emphasis on academic excellence","deadline":"January annually","highlight":"Partial or full tuition coverage; non-need-based merit scholarship."},
{"id":"finland-futura-foundation","name":"Foundation for Economic Education (SEFE) Scholarship","country":"Finland","level":"Master's","type":"University","amount":"Fully funded (tuition + €11,000/yr)","who":"Outstanding international Master's students, especially in STEM and business","deadline":"December annually","highlight":"Covers tuition and living costs; emphasizes academic merit and potential."},
{"id":"finland-aalto-scholarship","name":"Aalto Doctoral & Master's Scholarship Program","country":"Finland","level":"Master's","type":"University","amount":"€5,000–15,000/yr + potential tuition waiver","who":"International Master's applicants with strong academic records and research potential","deadline":"January annually","highlight":"Focus on innovation and sustainability-focused programs."},
{"id":"denmark-dtu-excellence","name":"DTU Excellence Scholarship","country":"Denmark","level":"Master's","type":"University","amount":"DKK 50,000–120,000/yr (~€6,700–16,000) + possible tuition waiver","who":"International engineering and science Master's students with exceptional credentials","deadline":"January annually","highlight":"Targets top performers in STEM; partial/full tuition support possible."},
{"id":"denmark-cbs-scholarship","name":"Copenhagen Business School Scholarship Programme","country":"Denmark","level":"Master's","type":"University","amount":"DKK 40,000–80,000/yr (~€5,300–10,700)","who":"Master's students in business, economics, and management with strong academic profile","deadline":"November annually","highlight":"Merit-based; partial tuition coverage for qualifying candidates."},
{"id":"uae-emirates-scholarship","name":"UAE Government Higher Education Scholarship","country":"United Arab Emirates","level":"Master's","type":"Government","amount":"Fully funded (tuition + AED 10,000/month)","who":"International Master's students in STEM, healthcare, and strategic sectors; limited slots","deadline":"Varies (contact Ministry of Education)","highlight":"Covers tuition and monthly stipend; highly selective; includes living allowance."},
{"id":"uae-nyu-ad-scholarship","name":"NYU Abu Dhabi Global Scholarship","country":"United Arab Emirates","level":"Master's","type":"University","amount":"AED 100,000–220,000/yr (~€27,000–59,500 tuition coverage)","who":"Master's applicants with exceptional academic and leadership potential","deadline":"May annually","highlight":"Need-based and merit-based awards; NYC-caliber education in Middle East hub."},
{"id":"spain-la-caixa-foundation","name":"La Caixa Foundation Scholarship for International Master's","country":"Spain","level":"Master's","type":"Government","amount":"€1,000–1,500/month + tuition waiver","who":"International Master's students at participating Spanish universities; merit and need-based","deadline":"April/May annually","highlight":"Competitive; covers tuition and living costs for Spain's top institutions."},
{"id":"spain-fundacion-carolina","name":"Fundación Carolina Scholarship","country":"Spain","level":"Master's","type":"Government","amount":"€800–1,200/month + tuition waiver","who":"International Master's students in engineering, business, and STEM from select countries","deadline":"March annually","highlight":"Emphasis on career development and Spain-home country economic ties."},
{"id":"poland-meys-scholarship","name":"Ministry of Education and Science (MES) Scholarship","country":"Poland","level":"Master's","type":"Government","amount":"€1,000–1,500/month","who":"International Master's students in accredited Polish public universities","deadline":"April/May annually","highlight":"Government-funded; partial living support; limited slots."},
{"id":"poland-poland-buddy","name":"Polish Ministry/University Partnership Grants (India)","country":"Poland","level":"Master's","type":"Government","amount":"€3,000–6,000/yr + possible tuition waiver","who":"Indian students pursuing Medicine, Engineering, or Computer Science Master's in Poland","deadline":"May/June annually","highlight":"Bilateral India-Poland initiative; priority for engineering and medical fields."},
{"id":"czech-republic-meys","name":"Czech Ministry of Education Scholarship","country":"Czech Republic","level":"Master's","type":"Government","amount":"CZK 15,000–25,000/month (~€600–1,000)","who":"International Master's students at public Czech universities; merit-based selection","deadline":"March/April annually","highlight":"Covers partial living costs; government-funded; merit-based selection."},
{"id":"czech-republic-charles-global","name":"Charles University Global Scholarship Programme","country":"Czech Republic","level":"Master's","type":"University","amount":"CZK 20,000–30,000/month (~€800–1,200) + tuition waiver","who":"High-achieving international Master's students across all disciplines","deadline":"January/February annually","highlight":"Prague's flagship university; merit-based; partial/full support based on profile."},

    // ─── USA ───
    { id: "fulbright", name: "Fulbright Foreign Student Program", country: "USA", level: "Master's & PhD", type: "Government", amount: "Fully funded", who: "International students; apply via your home-country Fulbright commission", deadline: "Feb–Oct (varies by country)", highlight: "The flagship US government scholarship — tuition, living, airfare & insurance." },
    { id: "knight-hennessy", name: "Knight-Hennessy Scholars", country: "USA", level: "Master's & PhD", type: "University", amount: "Fully funded", who: "Any graduate programme at Stanford; strong leadership", deadline: "October", highlight: "Stanford's elite fully-funded graduate scholarship across all schools." },
    { id: "aauw", name: "AAUW International Fellowships", country: "USA", level: "Master's & PhD", type: "Merit (Women)", amount: "$20,000–50,000", who: "Women who are not US citizens", deadline: "November", highlight: "Supports women pursuing graduate study in the US." },
    { id: "fulbright-nehru", name: "Fulbright-Nehru Master's Fellowship", country: "USA", level: "Master's", type: "Government", amount: "Fully funded", who: "Indian citizens with 3+ yrs experience", deadline: "May", highlight: "India-specific Fulbright track — fully funded US master's." },

    // ─── UK ───
    { id: "chevening", name: "Chevening Scholarship", country: "UK", level: "Master's", type: "Government", amount: "Fully funded", who: "Leadership potential + 2 yrs work experience", deadline: "November", highlight: "The UK government's global one-year master's scholarship." },
    { id: "commonwealth", name: "Commonwealth Scholarship", country: "UK", level: "Master's & PhD", type: "Government", amount: "Fully funded", who: "Citizens of Commonwealth countries", deadline: "October–December", highlight: "Full funding for students from Commonwealth nations." },
    { id: "gates-cambridge", name: "Gates Cambridge Scholarship", country: "UK", level: "Master's & PhD", type: "University", amount: "Fully funded", who: "Outstanding applicants to Cambridge (non-UK)", deadline: "October/December", highlight: "Cambridge's most prestigious international scholarship." },
    { id: "rhodes", name: "Rhodes Scholarship", country: "UK", level: "Master's", type: "University", amount: "Fully funded", who: "Exceptional students from eligible countries (Oxford)", deadline: "July–September", highlight: "The world's oldest graduate scholarship, at Oxford." },
    { id: "clarendon", name: "Clarendon Fund Scholarship", country: "UK", level: "Master's & PhD", type: "University", amount: "Fully funded", who: "Any graduate course at Oxford; academic excellence", deadline: "Jan (course deadline)", highlight: "Oxford's flagship merit scholarship — automatic consideration." },
    { id: "great", name: "GREAT Scholarships", country: "UK", level: "Master's", type: "Govt + University", amount: "£10,000", who: "Select countries incl. India", deadline: "Varies by university", highlight: "British Council partial-funding for one-year master's." },

    // ─── Germany & Europe ───
    { id: "daad", name: "DAAD Scholarships", country: "Germany", level: "Master's & PhD", type: "Government", amount: "€934/month + extras", who: "International graduates", deadline: "Varies (often Oct)", highlight: "Germany's main funding body — monthly stipend, travel, insurance." },
    { id: "erasmus", name: "Erasmus Mundus Joint Masters", country: "Europe (Multiple)", level: "Master's", type: "EU Government", amount: "Fully funded", who: "Study in 2+ European countries", deadline: "Oct–Jan", highlight: "Prestigious multi-country EU master's, fully funded." },
    { id: "eiffel", name: "Eiffel Excellence Scholarship", country: "France", level: "Master's & PhD", type: "Government", amount: "€1,181/month", who: "International students; nominated by the institution", deadline: "January", highlight: "French government scholarship for top international talent." },
    { id: "swiss-excellence", name: "Swiss Government Excellence", country: "Switzerland", level: "PhD & Research", type: "Government", amount: "Fully funded", who: "Researchers & postgrads from eligible countries", deadline: "Sep–Dec", highlight: "Funds research/PhD at Swiss universities." },
    { id: "holland", name: "Holland Scholarship", country: "Netherlands", level: "UG & Master's", type: "Govt + University", amount: "€5,000 (year 1)", who: "Non-EEA students", deadline: "February/May", highlight: "Dutch government + university partial scholarship." },

    // ─── Canada ───
    { id: "vanier", name: "Vanier Canada Graduate Scholarship", country: "Canada", level: "PhD", type: "Government", amount: "CAD 50,000/yr (3 yrs)", who: "Doctoral students; leadership + research", deadline: "Sep–Nov", highlight: "Canada's top doctoral scholarship." },
    { id: "pearson", name: "Lester B. Pearson Scholarship", country: "Canada", level: "Undergraduate", type: "University", amount: "Fully funded", who: "Exceptional international undergrads (U of Toronto)", deadline: "November", highlight: "U of Toronto's premier international UG award." },
    { id: "cgs", name: "Canada Graduate Scholarships", country: "Canada", level: "Master's & PhD", type: "Government", amount: "CAD 17,500–50,000", who: "Master's & doctoral students", deadline: "Dec", highlight: "Federal funding across Canadian universities." },

    // ─── Australia & NZ ───
    { id: "australia-awards", name: "Australia Awards", country: "Australia", level: "Master's", type: "Government", amount: "Fully funded", who: "Developing-country citizens", deadline: "April–June", highlight: "Australian govt scholarship — tuition, living, travel." },
    { id: "rtp", name: "Research Training Program (RTP)", country: "Australia", level: "Master's & PhD (research)", type: "Government", amount: "Fully funded + stipend", who: "Domestic & international research students", deadline: "Aug–Oct", highlight: "Funds research degrees at Australian universities." },
    { id: "nz-scholarships", name: "New Zealand Scholarships", country: "New Zealand", level: "Master's & PhD", type: "Government", amount: "Fully funded", who: "Citizens of eligible countries", deadline: "Feb–March", highlight: "NZ government full scholarship including living costs." },

    // ─── Asia ───
    { id: "mext", name: "MEXT Scholarship", country: "Japan", level: "UG / Master's / PhD", type: "Government", amount: "Fully funded", who: "International students; embassy or university route", deadline: "April–June", highlight: "Japanese government scholarship — no tuition + monthly stipend." },
    { id: "schwarzman", name: "Schwarzman Scholars", country: "China", level: "Master's", type: "University", amount: "Fully funded", who: "Future global leaders (Tsinghua University)", deadline: "September", highlight: "One-year fully-funded master's in global affairs in Beijing." },

    // ─── For Indian students (study anywhere) ───
    { id: "inlaks", name: "Inlaks Shivdasani Scholarship", country: "USA / UK / Europe", level: "Master's", type: "Merit + Need", amount: "Up to $100,000", who: "Indian citizens under 30 with a top admit", deadline: "Feb–March", highlight: "Prestigious Indian scholarship for study at top global universities." },
    { id: "kc-mahindra", name: "KC Mahindra Scholarship", country: "Multiple", level: "Master's", type: "Merit + Need", amount: "Up to ₹10 lakh (interest-free)", who: "Indian graduates going abroad", deadline: "March–April", highlight: "Long-running Indian scholarship loan for overseas master's." },
    { id: "aga-khan", name: "Aga Khan Foundation ISP", country: "Multiple", level: "Master's & PhD", type: "Need-based", amount: "50% grant + 50% loan", who: "Students from select developing countries", deadline: "Varies (often March)", highlight: "Need-based support for postgraduate study abroad." },
  ];

  window.LP_SCHOLARSHIPS = S;
  window.LP_SCHOLARSHIP_COUNTRIES = [...new Set(S.map(s => s.country))];
})();
