"use strict";
(function() {
  const S = [
    { "id": "france-bgf-scholarship", "name": "BGF (Bourse du Gouvernement Fran\xE7ais) Master's Scholarship", "country": "France", "level": "Master's", "type": "Government", "amount": "\u20AC600\u20131,000/month + tuition waiver", "who": "International students from eligible countries enrolled in French public Master's programs", "deadline": "Varies (Spring for next academic year)", "highlight": "Covers living costs and tuition at public universities; competitive selection." },
    { "id": "france-erasmus-mundus", "name": "Erasmus Mundus Joint Master's Scholarships", "country": "France", "level": "Master's", "type": "Erasmus", "amount": "\u20AC1,400/month + full tuition", "who": "Students pursuing joint Master's degrees offered by European consortiums (many based in France)", "deadline": "December/January annually", "highlight": "Study across 2\u20133 European countries; includes mobility and living allowance." },
    { "id": "italy-italian-government", "name": "Italian Government Scholarship for International Students", "country": "Italy", "level": "Master's", "type": "Government", "amount": "\u20AC900\u20131,200/month + tuition waiver", "who": "International Master's students enrolled at public Italian universities; merit-based selection", "deadline": "March/April annually", "highlight": "Covers living costs and waives tuition; competitive pool." },
    { "id": "italy-sapienza-partnership", "name": "Sapienza University Partnership Scholarships (India Focus)", "country": "Italy", "level": "Master's", "type": "University", "amount": "\u20AC5,000\u201310,000/yr", "who": "Indian students pursuing Master's in Engineering, Computer Science, or Management at Sapienza", "deadline": "April annually", "highlight": "Dedicated partnership with Indian universities; partial tuition coverage." },
    { "id": "sweden-kth-excellence", "name": "KTH Excellence Scholarships", "country": "Sweden", "level": "Master's", "type": "University", "amount": "Fully funded (tuition + SEK 12,000/month)", "who": "High-achieving international students in engineering and tech Master's programs", "deadline": "December/January annually", "highlight": "Covers full tuition and living costs; limited availability; highly competitive." },
    { "id": "sweden-lund-scholarship", "name": "Lund University Global Scholarship Programme", "country": "Sweden", "level": "Master's", "type": "University", "amount": "SEK 80,000\u2013140,000/yr (~\u20AC8,000\u201314,000)", "who": "International Master's students at Lund; merit-based with emphasis on academic excellence", "deadline": "January annually", "highlight": "Partial or full tuition coverage; non-need-based merit scholarship." },
    { "id": "finland-futura-foundation", "name": "Foundation for Economic Education (SEFE) Scholarship", "country": "Finland", "level": "Master's", "type": "University", "amount": "Fully funded (tuition + \u20AC11,000/yr)", "who": "Outstanding international Master's students, especially in STEM and business", "deadline": "December annually", "highlight": "Covers tuition and living costs; emphasizes academic merit and potential." },
    { "id": "finland-aalto-scholarship", "name": "Aalto Doctoral & Master's Scholarship Program", "country": "Finland", "level": "Master's", "type": "University", "amount": "\u20AC5,000\u201315,000/yr + potential tuition waiver", "who": "International Master's applicants with strong academic records and research potential", "deadline": "January annually", "highlight": "Focus on innovation and sustainability-focused programs." },
    { "id": "denmark-dtu-excellence", "name": "DTU Excellence Scholarship", "country": "Denmark", "level": "Master's", "type": "University", "amount": "DKK 50,000\u2013120,000/yr (~\u20AC6,700\u201316,000) + possible tuition waiver", "who": "International engineering and science Master's students with exceptional credentials", "deadline": "January annually", "highlight": "Targets top performers in STEM; partial/full tuition support possible." },
    { "id": "denmark-cbs-scholarship", "name": "Copenhagen Business School Scholarship Programme", "country": "Denmark", "level": "Master's", "type": "University", "amount": "DKK 40,000\u201380,000/yr (~\u20AC5,300\u201310,700)", "who": "Master's students in business, economics, and management with strong academic profile", "deadline": "November annually", "highlight": "Merit-based; partial tuition coverage for qualifying candidates." },
    { "id": "uae-emirates-scholarship", "name": "UAE Government Higher Education Scholarship", "country": "United Arab Emirates", "level": "Master's", "type": "Government", "amount": "Fully funded (tuition + AED 10,000/month)", "who": "International Master's students in STEM, healthcare, and strategic sectors; limited slots", "deadline": "Varies (contact Ministry of Education)", "highlight": "Covers tuition and monthly stipend; highly selective; includes living allowance." },
    { "id": "uae-nyu-ad-scholarship", "name": "NYU Abu Dhabi Global Scholarship", "country": "United Arab Emirates", "level": "Master's", "type": "University", "amount": "AED 100,000\u2013220,000/yr (~\u20AC27,000\u201359,500 tuition coverage)", "who": "Master's applicants with exceptional academic and leadership potential", "deadline": "May annually", "highlight": "Need-based and merit-based awards; NYC-caliber education in Middle East hub." },
    { "id": "spain-la-caixa-foundation", "name": "La Caixa Foundation Scholarship for International Master's", "country": "Spain", "level": "Master's", "type": "Government", "amount": "\u20AC1,000\u20131,500/month + tuition waiver", "who": "International Master's students at participating Spanish universities; merit and need-based", "deadline": "April/May annually", "highlight": "Competitive; covers tuition and living costs for Spain's top institutions." },
    { "id": "spain-fundacion-carolina", "name": "Fundaci\xF3n Carolina Scholarship", "country": "Spain", "level": "Master's", "type": "Government", "amount": "\u20AC800\u20131,200/month + tuition waiver", "who": "International Master's students in engineering, business, and STEM from select countries", "deadline": "March annually", "highlight": "Emphasis on career development and Spain-home country economic ties." },
    { "id": "poland-meys-scholarship", "name": "Ministry of Education and Science (MES) Scholarship", "country": "Poland", "level": "Master's", "type": "Government", "amount": "\u20AC1,000\u20131,500/month", "who": "International Master's students in accredited Polish public universities", "deadline": "April/May annually", "highlight": "Government-funded; partial living support; limited slots." },
    { "id": "poland-poland-buddy", "name": "Polish Ministry/University Partnership Grants (India)", "country": "Poland", "level": "Master's", "type": "Government", "amount": "\u20AC3,000\u20136,000/yr + possible tuition waiver", "who": "Indian students pursuing Medicine, Engineering, or Computer Science Master's in Poland", "deadline": "May/June annually", "highlight": "Bilateral India-Poland initiative; priority for engineering and medical fields." },
    { "id": "czech-republic-meys", "name": "Czech Ministry of Education Scholarship", "country": "Czech Republic", "level": "Master's", "type": "Government", "amount": "CZK 15,000\u201325,000/month (~\u20AC600\u20131,000)", "who": "International Master's students at public Czech universities; merit-based selection", "deadline": "March/April annually", "highlight": "Covers partial living costs; government-funded; merit-based selection." },
    { "id": "czech-republic-charles-global", "name": "Charles University Global Scholarship Programme", "country": "Czech Republic", "level": "Master's", "type": "University", "amount": "CZK 20,000\u201330,000/month (~\u20AC800\u20131,200) + tuition waiver", "who": "High-achieving international Master's students across all disciplines", "deadline": "January/February annually", "highlight": "Prague's flagship university; merit-based; partial/full support based on profile." },
    // ─── USA ───
    { id: "fulbright", name: "Fulbright Foreign Student Program", country: "USA", level: "Master's & PhD", type: "Government", amount: "Fully funded", who: "International students; apply via your home-country Fulbright commission", deadline: "Feb\u2013Oct (varies by country)", highlight: "The flagship US government scholarship \u2014 tuition, living, airfare & insurance.", official: "https://foreign.fulbrightonline.org/" },
    { id: "knight-hennessy", name: "Knight-Hennessy Scholars", country: "USA", level: "Master's & PhD", type: "University", amount: "Fully funded", who: "Any graduate programme at Stanford; strong leadership", deadline: "October", highlight: "Stanford's elite fully-funded graduate scholarship across all schools.", official: "https://knight-hennessy.stanford.edu/" },
    { id: "aauw", name: "AAUW International Fellowships", country: "USA", level: "Master's & PhD", type: "Merit (Women)", amount: "$20,000\u201350,000", who: "Women who are not US citizens", deadline: "November", highlight: "Supports women pursuing graduate study in the US." },
    { id: "fulbright-nehru", name: "Fulbright-Nehru Master's Fellowship", country: "USA", level: "Master's", type: "Government", amount: "Fully funded", who: "Indian citizens with 3+ yrs experience", deadline: "May", highlight: "India-specific Fulbright track \u2014 fully funded US master's.", official: "https://www.usief.org.in/" },
    // ─── UK ───
    { id: "chevening", name: "Chevening Scholarship", country: "UK", level: "Master's", type: "Government", amount: "Fully funded", who: "Leadership potential + 2 yrs work experience", deadline: "November", highlight: "The UK government's global one-year master's scholarship.", official: "https://www.chevening.org/" },
    { id: "commonwealth", name: "Commonwealth Scholarship", country: "UK", level: "Master's & PhD", type: "Government", amount: "Fully funded", who: "Citizens of Commonwealth countries", deadline: "October\u2013December", highlight: "Full funding for students from Commonwealth nations.", official: "https://cscuk.fcdo.gov.uk/" },
    { id: "gates-cambridge", name: "Gates Cambridge Scholarship", country: "UK", level: "Master's & PhD", type: "University", amount: "Fully funded", who: "Outstanding applicants to Cambridge (non-UK)", deadline: "October/December", highlight: "Cambridge's most prestigious international scholarship.", official: "https://www.gatescambridge.org/" },
    { id: "rhodes", name: "Rhodes Scholarship", country: "UK", level: "Master's", type: "University", amount: "Fully funded", who: "Exceptional students from eligible countries (Oxford)", deadline: "July\u2013September", highlight: "The world's oldest graduate scholarship, at Oxford.", official: "https://www.rhodeshouse.ox.ac.uk/" },
    { id: "clarendon", name: "Clarendon Fund Scholarship", country: "UK", level: "Master's & PhD", type: "University", amount: "Fully funded", who: "Any graduate course at Oxford; academic excellence", deadline: "Jan (course deadline)", highlight: "Oxford's flagship merit scholarship \u2014 automatic consideration." },
    { id: "great", name: "GREAT Scholarships", country: "UK", level: "Master's", type: "Govt + University", amount: "\xA310,000", who: "Select countries incl. India", deadline: "Varies by university", highlight: "British Council partial-funding for one-year master's.", official: "https://study-uk.britishcouncil.org/scholarships-funding/great-scholarships" },
    // ─── Germany & Europe ───
    { id: "daad", name: "DAAD Scholarships", country: "Germany", level: "Master's & PhD", type: "Government", amount: "\u20AC934/month + extras", who: "International graduates", deadline: "Varies (often Oct)", highlight: "Germany's main funding body \u2014 monthly stipend, travel, insurance.", official: "https://www.daad.de/en/" },
    { id: "erasmus", name: "Erasmus Mundus Joint Masters", country: "Europe (Multiple)", level: "Master's", type: "EU Government", amount: "Fully funded", who: "Study in 2+ European countries", deadline: "Oct\u2013Jan", highlight: "Prestigious multi-country EU master's, fully funded.", official: "https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters" },
    { id: "eiffel", name: "Eiffel Excellence Scholarship", country: "France", level: "Master's & PhD", type: "Government", amount: "\u20AC1,181/month", who: "International students; nominated by the institution", deadline: "January", highlight: "French government scholarship for top international talent.", official: "https://www.campusfrance.org/en/france-excellence-eiffel-scholarship-program" },
    { id: "swiss-excellence", name: "Swiss Government Excellence", country: "Switzerland", level: "PhD & Research", type: "Government", amount: "Fully funded", who: "Researchers & postgrads from eligible countries", deadline: "Sep\u2013Dec", highlight: "Funds research/PhD at Swiss universities.", official: "https://www.sbfi.admin.ch/en/swiss-government-excellence-scholarships" },
    { id: "holland", name: "Holland Scholarship", country: "Netherlands", level: "UG & Master's", type: "Govt + University", amount: "\u20AC5,000 (year 1)", who: "Non-EEA students", deadline: "February/May", highlight: "Dutch government + university partial scholarship.", official: "https://www.studyinnl.org/finances/nl-scholarship" },
    // ─── Canada ───
    { id: "vanier", name: "Vanier Canada Graduate Scholarship", country: "Canada", level: "PhD", type: "Government", amount: "CAD 50,000/yr (3 yrs)", who: "Doctoral students; leadership + research", deadline: "Sep\u2013Nov", highlight: "Canada's top doctoral scholarship." },
    { id: "pearson", name: "Lester B. Pearson Scholarship", country: "Canada", level: "Undergraduate", type: "University", amount: "Fully funded", who: "Exceptional international undergrads (U of Toronto)", deadline: "November", highlight: "U of Toronto's premier international UG award.", official: "https://future.utoronto.ca/pearson-scholarships" },
    { id: "cgs", name: "Canada Graduate Scholarships", country: "Canada", level: "Master's & PhD", type: "Government", amount: "CAD 17,500\u201350,000", who: "Master's & doctoral students", deadline: "Dec", highlight: "Federal funding across Canadian universities.", official: "https://nserc-crsng.canada.ca/en/funding-opportunity/canada-graduate-research-scholarship-masters-program" },
    // ─── Australia & NZ ───
    { id: "australia-awards", name: "Australia Awards", country: "Australia", level: "Master's", type: "Government", amount: "Fully funded", who: "Developing-country citizens", deadline: "April\u2013June", highlight: "Australian govt scholarship \u2014 tuition, living, travel.", official: "https://www.dfat.gov.au/people-to-people/australia-awards" },
    { id: "rtp", name: "Research Training Program (RTP)", country: "Australia", level: "Master's & PhD (research)", type: "Government", amount: "Fully funded + stipend", who: "Domestic & international research students", deadline: "Aug\u2013Oct", highlight: "Funds research degrees at Australian universities.", official: "https://www.education.gov.au/research-block-grants/research-training-program" },
    { id: "nz-scholarships", name: "New Zealand Scholarships", country: "New Zealand", level: "Master's & PhD", type: "Government", amount: "Fully funded", who: "Citizens of eligible countries", deadline: "Feb\u2013March", highlight: "NZ government full scholarship including living costs.", official: "https://www.nzscholarships.govt.nz/" },
    // ─── Asia ───
    { id: "mext", name: "MEXT Scholarship", country: "Japan", level: "UG / Master's / PhD", type: "Government", amount: "Fully funded", who: "International students; embassy or university route", deadline: "April\u2013June", highlight: "Japanese government scholarship \u2014 no tuition + monthly stipend.", official: "https://www.studyinjapan.go.jp/en/planning/scholarships/" },
    { id: "schwarzman", name: "Schwarzman Scholars", country: "China", level: "Master's", type: "University", amount: "Fully funded", who: "Future global leaders (Tsinghua University)", deadline: "September", highlight: "One-year fully-funded master's in global affairs in Beijing.", official: "https://www.schwarzmanscholars.org/" },
    // ─── For Indian students (study anywhere) ───
    { id: "inlaks", name: "Inlaks Shivdasani Scholarship", country: "USA / UK / Europe", level: "Master's", type: "Merit + Need", amount: "Up to $100,000", who: "Indian citizens under 30 with a top admit", deadline: "Feb\u2013March", highlight: "Prestigious Indian scholarship for study at top global universities.", official: "https://inlaksfoundation.org/" },
    { id: "kc-mahindra", name: "KC Mahindra Scholarship", country: "Multiple", level: "Master's", type: "Merit + Need", amount: "Up to \u20B910 lakh (interest-free)", who: "Indian graduates going abroad", deadline: "March\u2013April", highlight: "Long-running Indian scholarship loan for overseas master's.", official: "https://www.kcmet.org/index.aspx" },
    { id: "aga-khan", name: "Aga Khan Foundation ISP", country: "Multiple", level: "Master's & PhD", type: "Need-based", amount: "50% grant + 50% loan", who: "Students from select developing countries", deadline: "Varies (often March)", highlight: "Need-based support for postgraduate study abroad.", official: "https://the.akdn/en/what-we-do/developing-human-capacity/education/international-scholarships" }
  ];
  window.LP_SCHOLARSHIPS = S;
  window.LP_SCHOLARSHIP_COUNTRIES = [...new Set(S.map((s) => s.country))];
})();
