// SOP / LOR / motivation-letter sample library — used by the static SEO generator
// (scripts/generate-seo-pages.mjs) to build /sop-samples/<id>/ pages, and available to
// the SPA if needed. Every sample is an ORIGINAL, illustrative template written by the
// LandingPrep editorial team — realistic but fictional (no real person's essay), meant to
// be adapted, never copied. Admissions systems run plagiarism checks, so copying any
// online sample (including this one) will hurt an application.
window.LP_SOP_SAMPLES = [
  {
    id: "ms-computer-science-sop-sample",
    type: "Statement of Purpose",
    course: "MS in Computer Science",
    title: "MS in Computer Science SOP Sample (Statement of Purpose)",
    metaDesc: "A free, complete MS in Computer Science SOP sample with a paragraph-by-paragraph breakdown, common mistakes and a free SOP builder. Adapt it — never copy.",
    kw: "ms in computer science sop sample, sop for ms in cs, statement of purpose computer science, ms cs sop example, sop sample for masters in computer science usa",
    quick: "A strong MS in Computer Science Statement of Purpose opens with a specific motivation (not a childhood cliché), then proves your readiness with concrete projects, research or work, names the exact program, courses and professors you want, and closes with clear, realistic career goals. Below is a complete sample to study and adapt — never copy it, because admissions systems check for plagiarism.",
    sampleIntro: "Use this as a structural model. Replace every fact with your own — your projects, your numbers, your target lab. The goal is to sound like exactly one person: you.",
    sample: [
      "When a single unindexed query brought our college fest's registration site down on launch night, I spent the next six hours rewriting it with proper database indexing and a caching layer. We went from 4-second page loads to under 200 milliseconds and handled 9,000 sign-ups without another crash. That night turned an abstract interest in computer science into a concrete one: I wanted to understand systems deeply enough to design them so they never fail under load.",
      "I am applying to the Master of Science in Computer Science at [University] to specialise in distributed systems and machine-learning infrastructure. Over my bachelor's in Computer Science at [University], I built a foundation in algorithms, operating systems and databases, graduating with a [GPA] GPA and a final-year project on fault-tolerant key-value stores. Beyond coursework, I interned for six months at [Company], where I cut the latency of a recommendation pipeline by 38% by replacing nightly batch jobs with an incremental streaming design — a change now serving roughly two million daily users.",
      "Two experiences shaped my research interest. First, my undergraduate thesis on consensus protocols, where I implemented a simplified Raft from the paper and measured how leader-election timing affected throughput, taught me how much careful engineering hides behind a clean abstraction. Second, a reading group on large-scale ML systems showed me that the hardest problems today are not only in the models but in the infrastructure that trains and serves them reliably and cheaply.",
      "[University]'s program is a strong fit for exactly these interests. I am drawn to Professor [Name]'s work on [specific area] — their recent paper on [topic] directly addresses the scheduling problem I ran into during my internship. I would also value the [specific course] and [specific course] electives, and the chance to contribute to the [specific lab or group]. I have read several publications from the group and believe my systems background and hands-on infrastructure experience would let me contribute quickly.",
      "After the program, I intend to work as a systems or machine-learning-infrastructure engineer at a company building large-scale platforms, with the longer-term goal of leading an infrastructure team and, eventually, returning to teach. I am applying for a master's rather than going straight to industry because I want the depth — the formal grounding in distributed systems theory and the research experience — that will let me design the next generation of these systems rather than only maintaining them. I am confident that [University] is where I can build that depth, and I would be glad to bring my energy and engineering experience to your program.",
    ],
    structure: [
      ["Opening hook (1 paragraph)", "A specific, true moment that sparked your interest — concrete and personal, never a generic 'since childhood I loved computers'."],
      ["Academic & professional background (1–2 paragraphs)", "Your degree, GPA if strong, key projects, internships and measurable results. Use numbers — they prove impact."],
      ["Why this field / research interest (1 paragraph)", "What specific area you want to go deeper in, and the experiences that led you there."],
      ["Why THIS program (1 paragraph)", "Name the university, exact professors, labs and courses. This is the paragraph generic essays skip — and it's the one that wins."],
      ["Career goals & close (1 paragraph)", "Realistic short- and long-term goals, and why a master's (not just a job) is the right next step."],
    ],
    mistakes: [
      "Starting with a cliché ('Ever since I was a child…') — admissions readers see thousands of these.",
      "Listing your CV in prose instead of telling a focused story with a few strong examples.",
      "Writing one generic SOP and sending it to every university — reusing it without naming each program's professors and courses is the #1 reason strong profiles get rejected.",
      "Vague claims ('I am passionate and hardworking') with no evidence. Show, don't assert.",
      "Copying an online sample. Plagiarism checks will flag it and it instantly destroys trust.",
    ],
  },
  {
    id: "ms-data-science-sop-sample",
    type: "Statement of Purpose",
    course: "MS in Data Science",
    title: "MS in Data Science SOP Sample (Statement of Purpose)",
    metaDesc: "A free, complete MS in Data Science SOP sample with a paragraph-by-paragraph structure, common mistakes and a free SOP builder. Adapt it to your own story — never copy.",
    kw: "ms in data science sop sample, sop for data science, statement of purpose data science, data science sop example, ms data science personal statement",
    quick: "A convincing MS in Data Science Statement of Purpose connects a real problem you cared about to the data skills you built to solve it, shows measurable impact, and names the specific program, courses and faculty you want. Study the complete sample below and adapt it to your own story — never copy it, because universities run plagiarism checks.",
    sampleIntro: "Treat this as scaffolding. Swap in your own dataset, your own metric, your own target faculty — the structure stays, the substance must be entirely yours.",
    sample: [
      "During a public-health internship, I was handed three years of messy clinic records and one question: why were follow-up rates falling? After two weeks of cleaning, joining and modelling the data, I found that a single scheduling change had quietly doubled wait times for one patient group. The clinic reversed the change and follow-ups recovered within a month. I had expected data science to be about algorithms; that project taught me it is really about asking the right question and being trusted with the answer.",
      "I am applying to the Master of Science in Data Science at [University] to deepen my foundation in statistical modelling and machine learning and to learn to deploy it responsibly. I completed my bachelor's in [field] with a [GPA] GPA, including coursework in statistics, linear algebra and programming, and I have since worked for [duration] as a data analyst at [Company], where I built dashboards and predictive models that informed [specific decision], reducing [specific metric] by [number]%.",
      "My technical toolkit includes Python, SQL and R, with hands-on experience in scikit-learn, pandas and cloud data warehouses. But I have also seen the limits of self-teaching: I can fit a model, yet I want the rigorous grounding in probability, experimental design and causal inference that separates a reliable analysis from a misleading one. A formal master's is the fastest honest way for me to close that gap.",
      "[University]'s program fits my goals precisely. Professor [Name]'s research on [specific area] mirrors the causal questions I struggled with at work, and the [specific course] and [specific course] modules cover exactly the statistical depth I am missing. I am also drawn to the program's [capstone / industry project], which would let me apply these methods to a real organisation before I graduate.",
      "In the short term, I want to work as a data scientist on problems with real social or business impact — healthcare, public policy or sustainability. In the longer term, I hope to lead a data team and help set the standards for how data is used ethically and transparently. I am applying now because the next step in my growth is depth, not just more experience, and I am confident [University] is where I can build it.",
    ],
    structure: [
      ["Opening hook (1 paragraph)", "A real problem you solved (or failed to solve) with data — specific and human, with a clear outcome."],
      ["Academic & work background (1 paragraph)", "Degree, GPA if strong, and concrete analytical work with measurable results."],
      ["Skills & the gap (1 paragraph)", "What you can already do, and honestly what depth you still need — this justifies the master's."],
      ["Why THIS program (1 paragraph)", "Named faculty, courses, capstone or labs that match your interests."],
      ["Career goals & close (1 paragraph)", "Specific short- and long-term goals and why now is the right time."],
    ],
    mistakes: [
      "Buzzword soup ('big data, AI, deep learning') with no real project behind it.",
      "Only naming tools (Python, Tableau) instead of showing what you discovered or changed with them.",
      "Ignoring statistics and ethics — top programs want rigour and responsibility, not just model accuracy.",
      "Not customising the 'why this program' paragraph for each university.",
      "Copying a sample essay — plagiarism detection will catch it.",
    ],
  },
  {
    id: "mba-sop-sample",
    type: "Statement of Purpose",
    course: "MBA",
    title: "MBA SOP / Statement of Purpose Sample",
    metaDesc: "A free, complete MBA Statement of Purpose sample with structure, common mistakes and a free SOP builder. Adapt the framework to your own leadership story — never copy.",
    kw: "mba sop sample, statement of purpose for mba, mba personal statement example, mba application essay sample, why mba essay sample",
    quick: "A strong MBA Statement of Purpose is built around leadership and impact: a clear career goal, the specific gap an MBA fills, evidence that you have already led and delivered results, and exactly why this school's program and community fit your plan. Study the complete sample below and adapt the framework to your own story — never copy it.",
    sampleIntro: "MBA essays reward self-awareness and specifics. Use this structure, but ground every claim in your own promotions, teams led and numbers delivered.",
    sample: [
      "Eighteen months ago I was promoted to lead a team of seven after our regional sales fell for three straight quarters. I rebuilt the pipeline process, introduced weekly coaching and renegotiated two key accounts personally; within a year the region grew 22% and became the company's fastest-improving. I learned that I could turn a struggling team around — but I also hit a ceiling. To move from running a region to shaping a company's strategy, I need the financial, operational and leadership grounding that an MBA provides.",
      "My goal is clear: in the short term, to move into strategy or general management in the technology sector; in the long term, to lead a business unit and eventually start a company that brings affordable financial tools to underserved markets. I have the commercial instinct and the people skills; what I lack is the formal training in corporate finance, operations and global strategy — and the network of peers who will challenge and sharpen me.",
      "Over five years at [Company] I progressed from analyst to team lead, consistently taking on the problems no one wanted: a failing product line I helped reposition, a cross-functional launch I coordinated across three countries, and a mentoring program I founded that is still running. Each taught me that results come from aligning people, not just plans — a lesson I want to test and refine against the hardest cases in a classroom of equally driven peers.",
      "[School]'s MBA fits this plan precisely. The [specific concentration or course] and Professor [Name]'s work on [topic] address exactly the strategic gaps I have identified. I am drawn to the [specific club, leadership lab or experiential project], where I could lead a real consulting engagement before graduating, and to the school's strong [industry] recruiting network. After a campus visit and conversations with two alumni, I am confident this community matches both my ambition and my values.",
      "I am applying now because I have enough experience to contribute real cases to discussions, and enough humility to know what I still need to learn. An MBA from [School] is the bridge between the leader I have become and the one I intend to be, and I am ready to bring my energy, my track record and my commitment to the class.",
    ],
    structure: [
      ["Leadership hook (1 paragraph)", "A specific moment you led and delivered measurable results — and the ceiling you hit that an MBA breaks through."],
      ["Career goals (1 paragraph)", "Clear short- and long-term goals, and the exact gap (finance, strategy, network) the MBA fills."],
      ["Track record (1 paragraph)", "Progression, ownership of hard problems and what each taught you about leadership."],
      ["Why THIS school (1 paragraph)", "Named concentrations, professors, clubs, treks or experiential projects — show you researched it deeply."],
      ["Why now & close (1 paragraph)", "Why you are ready, what you'll contribute to the cohort, and a confident close."],
    ],
    mistakes: [
      "Vague goals ('I want to be a leader') — admissions committees want a specific, believable path.",
      "Listing achievements without reflection — they want the lesson, not just the trophy.",
      "Generic 'why our school' paragraphs that could apply to any program.",
      "Hiding failures entirely — a well-handled setback shows maturity.",
      "Reusing the essay verbatim across schools, or copying a sample. Both are easy to spot.",
    ],
  },
  {
    id: "scholarship-motivation-letter-sample",
    type: "Motivation Letter",
    course: "Scholarship application",
    title: "Scholarship Motivation Letter Sample",
    metaDesc: "A free, complete scholarship motivation letter sample with structure, common mistakes and a free builder. Adapt it to the scholarship's mission — never copy it.",
    kw: "scholarship motivation letter sample, motivation letter for scholarship, scholarship application essay sample, why i deserve this scholarship essay, scholarship statement sample",
    quick: "A winning scholarship motivation letter ties your story to the scholarship's specific mission: it shows genuine need or merit, concrete achievements, a clear plan for how you'll use the opportunity, and how you'll give back. Study the complete sample below and adapt it to the exact award you're applying for — never copy it.",
    sampleIntro: "Scholarship committees fund people, not just grades. Read the scholarship's mission first, then make this letter prove you embody it — with your own facts.",
    sample: [
      "I am applying for the [Scholarship Name] because its mission — [the scholarship's stated goal, e.g. supporting first-generation students in engineering] — describes both where I have come from and where I am determined to go. I am the first in my family to attend university, and I am applying to study [program] at [University] so that I can [specific goal that aligns with the scholarship].",
      "Studying has never been only about me. When my school had no functioning science lab, I and two classmates built a low-cost one from donated equipment and ran weekend sessions for younger students; over two years more than 120 of them attended, and four are now studying science at university. That experience taught me that resources change lives, and that I want to spend mine widening access to education and technology in communities like the one I grew up in.",
      "Academically, I have earned [GPA / rank] while working [part-time job] to support my studies, and I have led [specific role or project] that produced [measurable result]. The [Scholarship Name] would remove the financial barrier that currently limits my choices, letting me focus fully on my degree and the research and volunteering I want to pursue alongside it.",
      "With this support, my plan is concrete. During the program I will [specific academic and extracurricular plan]. After graduating, I intend to [specific career goal], and within [timeframe] to [specific way you will give back — mentor, build, fund, return to your community]. I see this scholarship not as a gift but as a responsibility I am ready to honour.",
      "Thank you for considering my application. The [Scholarship Name] stands for exactly what I want my career to stand for, and I would be proud to represent it. I am committed to making the most of the opportunity and to passing it on to others who, like me, simply need a door opened.",
    ],
    structure: [
      ["Mission match (1 paragraph)", "Open by linking your story directly to the scholarship's specific purpose."],
      ["Your defining story (1 paragraph)", "A concrete experience that shows your character, values and impact — not just your grades."],
      ["Merit & need (1 paragraph)", "Your achievements and, where relevant, the financial barrier the award removes."],
      ["Your plan & giving back (1 paragraph)", "Exactly how you'll use the opportunity and how you'll pay it forward."],
      ["Grateful, confident close (1 paragraph)", "Thank the committee and restate your commitment without begging."],
    ],
    mistakes: [
      "Generic letters that ignore the scholarship's specific mission — always read it first and mirror it honestly.",
      "Only listing grades — committees fund potential and character, not just marks.",
      "Over-the-top sob stories or flattery; be honest and specific instead.",
      "No plan for the future — they want to see the return on their investment in you.",
      "Copying a template word-for-word, or paying someone to write it — authenticity is the whole point.",
    ],
  },
  {
    id: "letter-of-recommendation-sample-masters",
    type: "Letter of Recommendation",
    course: "Master's application (academic referee)",
    title: "Letter of Recommendation (LOR) Sample for Master's — from a Professor",
    metaDesc: "A free, complete academic Letter of Recommendation (LOR) sample for a master's application, with structure and common mistakes. A template for referees to adapt — never copy.",
    kw: "letter of recommendation sample for masters, lor sample for ms, academic recommendation letter example, lor from professor sample, recommendation letter for graduate school",
    quick: "A strong academic Letter of Recommendation states how the referee knows the student and for how long, gives two or three specific examples of the student's ability, ranks them honestly against peers, and gives an explicit, confident recommendation. The complete sample below is a template for a professor to adapt with real, specific detail — generic letters help no one.",
    sampleIntro: "The best recommendation letters are specific and comparative. If you are a student, share your referee a 'brag sheet' of concrete examples; if you are a referee, replace every placeholder with a real observation.",
    sample: [
      "To the Admissions Committee,",
      "It is my pleasure to recommend [Student] for admission to the Master of Science in [program] at [University]. I am a Professor of [subject] at [University], and I have known [Student] for [duration], first as a student in my [course] class and later as a research assistant in my lab.",
      "[Student] stood out immediately. In a class of [number], they earned one of the top grades, but what impressed me more was the question they asked after a lecture on [topic] — it led to a side project in which they [specific accomplishment, e.g. re-implemented an algorithm and benchmarked it against the published results]. They pursued this on their own initiative, far beyond what the course required.",
      "When I invited [Student] to join my research on [topic], they proved equally strong at independent work. They [specific contribution], and when an early approach failed, they diagnosed the problem and proposed an alternative that worked — exactly the resilience graduate research demands. Among the [number] students I have supervised in the last [years] years, I would place [Student] in the top [percentage]%.",
      "Beyond their ability, [Student] is conscientious, collaborative and genuinely curious — the kind of student who lifts the people around them. I recommend them for your program without reservation, and I am confident they will thrive in and contribute to your community. Please feel free to contact me if I can provide any further detail.",
      "Sincerely,\n[Professor Name], [Title], [Department], [University] — [email]",
    ],
    structure: [
      ["Relationship (1 short paragraph)", "Who the referee is, and how and how long they have known the applicant."],
      ["Academic example (1 paragraph)", "A specific instance of the applicant's ability that goes beyond grades."],
      ["Research / independence example (1 paragraph)", "Evidence of initiative and resilience, plus an honest ranking against peers."],
      ["Character & recommendation (1 paragraph)", "Personal qualities and an explicit, confident endorsement."],
      ["Sign-off", "Full name, title, department and contact details — credibility matters."],
    ],
    mistakes: [
      "Vague praise ('a good student') with no specific examples — the #1 weakness in weak letters.",
      "No comparison or ranking — committees want to know how the applicant stacks up against peers.",
      "A letter that just repeats the applicant's CV instead of adding the referee's own observations.",
      "Letting the applicant write it and the professor sign without adding real detail — it reads generic.",
      "Copying a template without personalising it; admissions readers spot boilerplate instantly.",
    ],
  },
];
