// Bakes all slide-deck content into the browser-loaded slide-decks-data.jsx:
//  - keeps the 3 hand-authored inline decks (ielts-listening, german/french-basics)
//  - merges every data/decks-*.json pool authored for the other exam sections
//  - flips each plan entry to ready:true and wires its deck id (matched by exam+section)
// Re-run after editing any data/decks-*.json:  node scripts/build-decks.mjs
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import esbuild from "esbuild";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SRC = path.join(ROOT, "slide-decks-data.jsx");

// 1) Evaluate the current file to recover the 3 inline decks + the plan.
const code = esbuild.transformSync(fs.readFileSync(SRC, "utf8"), { loader: "jsx" }).code;
const win = {};
new Function("window", code)(win);
const inlineDecks = win.LP_SLIDE_DECKS || {};
const basePlan = win.LP_SLIDE_DECK_PLAN || [];

// 2) Merge every authored deck pool.
const merged = { ...inlineDecks };
for (const f of fs.readdirSync(path.join(ROOT, "data"))) {
  if (!/^decks-.*\.json$/.test(f)) continue;
  const pool = JSON.parse(fs.readFileSync(path.join(ROOT, "data", f), "utf8"));
  for (const [id, deck] of Object.entries(pool)) {
    if (!deck || !Array.isArray(deck.slides) || !deck.slides.length) throw new Error(`${f}: bad deck ${id}`);
    merged[id] = { id, ...deck };
  }
}

// 3) Build a (exam|section) -> id lookup, then mark plan entries ready.
const lookup = {};
for (const [id, d] of Object.entries(merged)) {
  if (d.exam && d.section) lookup[(d.exam + "|" + d.section).toLowerCase()] = id;
}
let readyCount = 0, soonCount = 0;
const plan = basePlan.map((group) => ({
  ...group,
  decks: group.decks.map((entry) => {
    if (entry.id && merged[entry.id]) { readyCount++; return { ...entry, ready: true }; }
    const id = lookup[(group.exam + "|" + entry.section).toLowerCase()];
    if (id) { readyCount++; return { ...entry, id, ready: true }; }
    soonCount++; return { ...entry, ready: false };
  }),
}));

// 4) Emit the generated file (compact data + tiny wiring).
const out = `/* global window */
"use strict";
// LandingPrep — "Prep Lessons": PPT-style slide-deck lessons per exam section.
// AUTO-GENERATED by scripts/build-decks.mjs. Edit the inline decks in git history or the
// data/decks-*.json pools, then re-run the script — do NOT hand-edit this file.
// Deck schema: { id, exam, examName, section, emoji, title, summary,
//   slides:[{ emoji, title, points:[...], example?:{label,text}, tip?, warn? }] }
(function () {
  window.LP_SLIDE_DECKS = ${JSON.stringify(merged)};
  window.LP_SLIDE_DECK_PLAN = ${JSON.stringify(plan)};
})();
`;
fs.writeFileSync(SRC, out);

const totalSlides = Object.values(merged).reduce((n, d) => n + d.slides.length, 0);
console.log(`Wrote slide-decks-data.jsx — ${Object.keys(merged).length} decks, ${totalSlides} slides, ${out.length} bytes`);
console.log(`Plan: ${readyCount} ready, ${soonCount} coming-soon`);
